const TURNPOINTS: Record<
  string,
  { name: string; added?: number; removed?: number }
> = {
  AB1: { name: "Aboyne Bridge" },
  ABA: { name: "Abbey St Bathans" },
  ABB: { name: "Abbot's Bromley" },
  ABD: { name: "Aboyne Dinnet" },
  ABE: { name: "Abergavenny" },
  ABF: { name: "Aberfeldy" },
  ABG: { name: "Abingdon Airfield" },
  ABI: { name: "Abington" },
  ABL: { name: "Aberfoyle" },
  ABN: { name: "Abingdon Bridge" },
  ABO: { name: "Aboyne" },
  ABP: { name: "Ashburnham" },
  ABR: { name: "Aberchirder" },
  ABS: { name: "Abergavenny SW" },
  ABY: { name: "Aberystwyth Pier" },
  ACB: { name: "Alconbury" },
  ACC: { name: "Accrington NE" },
  ACH: { name: "Achnasheen" },
  ACN: { name: "Achnabourin" },
  AD1: { name: "Aston Down Finish N" },
  AD2: { name: "Aston Down Finish S" },
  ADE: { name: "Aberdare SE" },
  ADF: { name: "Andoversford" },
  ADN: { name: "Aberdaron" },
  AFB: { name: "Alfriston Bridge" },
  AFD: { name: "Alford" },
  AGS: { name: "Abergele South" },
  AHA: { name: "Altnaharra" },
  AKE: { name: "Alnwick E" },
  ALB: { name: "Aln Bridge" },
  ALC: { name: "Alcester" },
  ALE: { name: "Aylesham" },
  ALF: { name: "Alfreton" },
  ALL: { name: "Allendale Bridge" },
  ALM: { name: "Alnwick Moor SW" },
  ALO: { name: "Alston" },
  ALR: { name: "Aberlour" },
  ALS: { name: "Alfreton South" },
  ALV: { name: "Alva" },
  ALW: { name: "Alton Southwest" },
  ALY: { name: "Alyth" },
  AMB: { name: "Amberley" },
  AMS: { name: "Ambleside" },
  AMU: { name: "Amulree" },
  AND: { name: "Andover SW" },
  ANE: { name: "Andover SE" },
  ANX: { name: "Ansty Cross" },
  APP: { name: "Appleby" },
  ARD: { name: "Ardvasar" },
  ARL: { name: "Ardrishaig Lighthouse" },
  ARU: { name: "Arundel" },
  ASB: { name: "Ashbury" },
  ASE: { name: "Ashford East" },
  ASH: { name: "Ashbourne" },
  ASP: { name: "Aspatria" },
  ASS: { name: "Ashford South" },
  AST: { name: "Aston Down" },
  ASW: { name: "Airdrie Southwest" },
  ASY: { name: "Ashley" },
  ATH: { name: "Atherstone" },
  ATT: { name: "Attleborough" },
  ATW: { name: "Alton Towers" },
  AUL: { name: "Auldgirth" },
  AVE: { name: "Avebury" },
  AVN: { name: "Avening" },
  AXM: { name: "Axminster" },
  AYL: { name: "Aylesbury" },
  AYS: { name: "Aysgarth" },
  BA1: { name: "Banbury W" },
  BA2: { name: "Banbury N" },
  BAA: { name: "Balallan" },
  BAB: { name: "Ballachulish Bridge" },
  BAC: { name: "Backwater Reservoir" },
  BAD: { name: "Badminton" },
  BAE: { name: "Bath East" },
  BAF: { name: "Balfron" },
  BAG: { name: "Bangor-on-Dee" },
  BAH: { name: "Barrhill" },
  BAK: { name: "Bakewell" },
  BAL: { name: "Bala" },
  BAM: { name: "Bampton" },
  BAN: { name: "Banbury" },
  BAR: { name: "Barnard Castle" },
  BAS: { name: "Basingstoke" },
  BAT: { name: "Bath Racecourse SW" },
  BAW: { name: "Banchory West" },
  BBG: { name: "Boat O'Brig" },
  BBK: { name: "Bracken Bank" },
  BBR: { name: "Bath Bridge" },
  BCA: { name: "Bishop's Caundle" },
  BCE: { name: "Banchory East" },
  BCL: { name: "Bishop's Cleeve NW" },
  BCN: { name: "Brechin" },
  BCS: { name: "Bishops Castle" },
  BCW: { name: "Bishops Cleeve W" },
  BCY: { name: "Banchory" },
  BDM: { name: "Bodmin SE" },
  BDN: { name: "Beadnell Harbour" },
  BDO: { name: "Balado" },
  BDW: { name: "Bodelwyddan" },
  BDY: { name: "Bardney" },
  BE2: { name: "Beal" },
  BEA: { name: "Beaminster" },
  BEC: { name: "Beckington" },
  BED: { name: "Bedford Bridge" },
  BEE: { name: "Beer Head W" },
  BEL: { name: "Bellingham" },
  BEM: { name: "Bembridge" },
  BEN: { name: "Bentpath" },
  BER: { name: "Berwick W" },
  BES: { name: "St Bees Head" },
  BET: { name: "Beattock" },
  BEU: { name: "Beulah" },
  BEV: { name: "Beverley" },
  BEW: { name: "Bewl Water" },
  BF1: { name: "Booker Finish SW" },
  BF2: { name: "Booker Finish NW" },
  BFD: { name: "Belford" },
  BFF: { name: "Banff" },
  BGA: { name: "Biggar" },
  BGG: { name: "Brigg" },
  BGO: { name: "Bangor SE" },
  BGR: { name: "Blairgowrie" },
  BGT: { name: "Bedlands Gate" },
  BGW: { name: "Basingstoke West" },
  BHN: { name: "Bath North" },
  BIC: { name: "Bicester Control Tower", removed: 2026 },
  BID: { name: "Bidford" },
  BIE: { name: "Bicester East" },
  BIF: { name: "Broughton-in-Furness" },
  BIG: { name: "Biggleswade" },
  BIL: { name: "Billinghay" },
  BIN: { name: "Biddenden" },
  BIR: { name: "Birdlip" },
  BIS: { name: "Bishop Auckland" },
  BKN: { name: "Bockleton" },
  BKY: { name: "Brinkley Church" },
  BLA: { name: "Blakehill Farm" },
  BLB: { name: "Barnstaple  Bridge" },
  BLD: { name: "Blandford" },
  BLE: { name: "Blenheim N" },
  BLF: { name: "Blaenau Ffestiniog" },
  BLG: { name: "Ballinluig" },
  BLH: { name: "Balloch" },
  BLI: { name: "Blidworth" },
  BLK: { name: "Blakeney Point" },
  BLN: { name: "Blanchland" },
  BLO: { name: "Bolsover SW" },
  BLR: { name: "Blair Atholl" },
  BLS: { name: "Barnsley S" },
  BLW: { name: "Barnsley W" },
  BLY: { name: "Bletchley" },
  BMA: { name: "Balmaha" },
  BMC: { name: "Brayford" },
  BMM: { name: "Brynamman" },
  BMR: { name: "Braemar East" },
  BMS: { name: "Barmouth Station" },
  BNG: { name: "Bingham" },
  BNK: { name: "Brinkworth" },
  BNS: { name: "Burn South-West" },
  BNV: { name: "Ben Nevis" },
  BNW: { name: "Bicester North West" },
  BO1: { name: "Booker SW" },
  BO4: { name: "Turville Windmill" },
  BO5: { name: "Rockwell End" },
  BOA: { name: "Bridge of Avon" },
  BOB: { name: "Booker M40 Bridge" },
  BOC: { name: "Bridge of Cally" },
  BOD: { name: "Bodiam" },
  BOG: { name: "Bridge of Gaur" },
  BOL: { name: "Bootle" },
  BOM: { name: "Bodmin SW" },
  BON: { name: "Boncath" },
  BOO: { name: "Booker Airfield" },
  BOR: { name: "Boroughbridge" },
  BOS: { name: "Boston" },
  BOT: { name: "Bottesford" },
  BOU: { name: "Bourne" },
  BOV: { name: "Bovey Tracey" },
  BOW: { name: "Bourton-on-the-water" },
  BOZ: { name: "Bozeat" },
  BPT: { name: "Bridport" },
  BR1: { name: "Bognor Regis Gliding Club" },
  BR2: { name: "Bognor Domes" },
  BRC: { name: "Brackley South" },
  BRD: { name: "Bradbury" },
  BRE: { name: "Brecon" },
  BRF: { name: "Bradford-on-avon" },
  BRG: { name: "Brenig" },
  BRH: { name: "Brough" },
  BRI: { name: "Bridgnorth" },
  BRK: { name: "Broad Oak" },
  BRL: { name: "Brill" },
  BRM: { name: "Bromsgrove" },
  BRN: { name: "Burn" },
  BRO: { name: "Broadway" },
  BRP: { name: "Brampton" },
  BRR: { name: "Brora" },
  BRS: { name: "Braemar Stadium" },
  BRT: { name: "Brent Tor" },
  BRU: { name: "Bruton" },
  BRY: { name: "Bromyard" },
  BRZ: { name: "Brenzett" },
  BS1: { name: "Bury St Edmunds S" },
  BS2: { name: "Bury St Edmunds N" },
  BSE: { name: "Bury St Edmunds" },
  BSN: { name: "Basingstoke N" },
  BSS: { name: "Bunessan Pier" },
  BSW: { name: "Brecon SW" },
  BT2: { name: "Bassenthwaite E" },
  BTH: { name: "Bassenthwaite Lake NW" },
  BTL: { name: "Battle" },
  BTN: { name: "Bridlington" },
  BTR: { name: "Ballater" },
  BTT: { name: "Buttermere" },
  BUB: { name: "Burbage" },
  BUC: { name: "Buckingham" },
  BUD: { name: "Bude" },
  BUG: { name: "Burley Gate" },
  BUH: { name: "Burnhope Reservoir" },
  BUI: { name: "Builth Wells" },
  BUK: { name: "Buckfastleigh" },
  BUL: { name: "Bullington" },
  BUN: { name: "Bungay" },
  BUS: { name: "Burton upon Stather" },
  BUT: { name: "Butser Hill" },
  BUX: { name: "Buxton" },
  BUY: { name: "Beauly" },
  BVR: { name: "Belvoir" },
  BVT: { name: "Bovington" },
  BWE: { name: "Bridgwater E" },
  BWL: { name: "Bwlch" },
  BYT: { name: "Blyth" },
  CAA: { name: "Callander NE" },
  CAC: { name: "Candover Church" },
  CAD: { name: "Callander" },
  CAE: { name: "Canterbury East" },
  CAH: { name: "Castle Howard" },
  CAI: { name: "Cairnwell" },
  CAL: { name: "Calvert Rail Junction" },
  CAN: { name: "Cannock" },
  CAO: { name: "Canonbie" },
  CAR: { name: "Carlton Moor" },
  CAS: { name: "Cambridge South" },
  CAT: { name: "Canterbury" },
  CAX: { name: "Caxton Gibbet" },
  CBA: { name: "Carter Bar" },
  CBC: { name: "Conisbrough Castle" },
  CBG: { name: "Creagan Bridge" },
  CBK: { name: "Carisbrooke Castle" },
  CBN: { name: "Chilbolton" },
  CBR: { name: "Carrbridge" },
  CCB: { name: "Catacol Bridge" },
  CCC: { name: "Carreg Cennen Castle" },
  CCH: { name: "Castle Combe" },
  CCK: { name: "Castle Carrock Dam NW" },
  CCL: { name: "Crickhowell" },
  CCR: { name: "Clay Cross Reservoir" },
  CCX: { name: "Cadbury Cross" },
  CDB: { name: "Cromdale Spey Bridge" },
  CDI: { name: "Cader Idris" },
  CDK: { name: "Clodock" },
  CDO: { name: "Castle Douglas SW" },
  CDS: { name: "Clattershaws Dam S" },
  CDW: { name: "Coldwaltham" },
  CER: { name: "Cerne Abbas" },
  CES: { name: "Cowes" },
  CFB: { name: "Chollerford Bridge" },
  CFE: { name: "Cranwell Finish East" },
  CFF: { name: "Crieff" },
  CFN: { name: "Chalford North" },
  CGB: { name: "Calgary Beach Car Park" },
  CGF: { name: "Corgarf" },
  CGI: { name: "Craigellachie" },
  CGL: { name: "Croglin" },
  CGN: { name: "Cragganmore" },
  CGT: { name: "Cherington" },
  CHA: { name: "Chard" },
  CHB: { name: "Charlbury" },
  CHC: { name: "Chipping Campden" },
  CHD: { name: "Chesterfield" },
  CHE: { name: "Chedworth" },
  CHI: { name: "Chichester W" },
  CHK: { name: "Chirk" },
  CHM: { name: "Charlton Mires" },
  CHN: { name: "Chipping Norton" },
  CHO: { name: "Chorley West" },
  CHP: { name: "Chipping" },
  CHR: { name: "Charterhall Field" },
  CHS: { name: "Chelmsford S" },
  CHT: { name: "Chatteris" },
  CHU: { name: "Church Houses" },
  CHV: { name: "Chieveley" },
  CHW: { name: "Charwelton" },
  CIL: { name: "Castle Island Laggan" },
  CIN: { name: "Cinderford" },
  CIR: { name: "Cirencester Church" },
  CIW: { name: "Cirencester West" },
  CKL: { name: "Chicklade" },
  CL2: { name: "Challock Chalk Pit" },
  CL3: { name: "Challock East" },
  CLA: { name: "Claydon" },
  CLC: { name: "Clacton E" },
  CLD: { name: "Culdrose A/f" },
  CLE: { name: "Clee" },
  CLH: { name: "Culmhead airfield" },
  CLI: { name: "Clitheroe" },
  CLK: { name: "Challock" },
  CLL: { name: "Carlisle" },
  CLM: { name: "Chilham" },
  CLN: { name: "Calne W" },
  CLO: { name: "Clova" },
  CLP: { name: "Clyffe Pypard" },
  CLR: { name: "Clare Church" },
  CLS: { name: "Culmstock" },
  CLT: { name: "Corran Lighthouse" },
  CLU: { name: "Clunas" },
  CLV: { name: "Cleeve Hill" },
  CLW: { name: "Carloway" },
  CLY: { name: "Callaly Castle" },
  CME: { name: "Cheltenham East" },
  CML: { name: "Carmodle" },
  CMN: { name: "Carmarthen" },
  CMO: { name: "Cockermouth" },
  CNB: { name: "Caerleon bridge" },
  CNE: { name: "Canterbury North East" },
  CNL: { name: "Connel" },
  CNN: { name: "Corndon Hill" },
  CNO: { name: "Carno" },
  CNR: { name: "Chinnor" },
  CNW: { name: "Cirencester nw" },
  CNY: { name: "Conwy Bridge" },
  COB: { name: "Corby South" },
  COC: { name: "Colchester" },
  COD: { name: "Coldstream" },
  COE: { name: "Corwen NE" },
  COF: { name: "Crocketford" },
  COG: { name: "Corby Glen" },
  COH: { name: "Coldingham" },
  COK: { name: "Cocking" },
  COM: { name: "Comrie" },
  CON: { name: "Condover" },
  COR: { name: "Corby" },
  COS: { name: "Cosford Junction" },
  COT: { name: "Colt Crag Reservoir" },
  COU: { name: "Coupar Angus" },
  COW: { name: "Colchester West" },
  CP1: { name: "Camphill start/finish south" },
  CP2: { name: "Camphill Chimney" },
  CPH: { name: "Camphill" },
  CPN: { name: "Clapham Reservoir N" },
  CPS: { name: "Chepstow S" },
  CPW: { name: "Chippenham W" },
  CRA: { name: "Cranwell North" },
  CRB: { name: "Cranbrook" },
  CRC: { name: "Crick" },
  CRD: { name: "Cricklade" },
  CRE: { name: "Crediton Station" },
  CRF: { name: "Crail" },
  CRG: { name: "Cerrig" },
  CRI: { name: "Crianlarich" },
  CRK: { name: "Crewkerne" },
  CRL: { name: "Crowland A/f" },
  CRM: { name: "Crymych Mast" },
  CRN: { name: "Crinan" },
  CRO: { name: "Crowland Bridge" },
  CRP: { name: "Cromer Pier" },
  CRR: { name: "Carron" },
  CRW: { name: "Crediton West" },
  CRY: { name: "Cray Reservoir" },
  CSD: { name: "Chirnside" },
  CSE: { name: "Canterbury South East" },
  CSF: { name: "Cosford Airfield" },
  CSK: { name: "Crask Bridge" },
  CSN: { name: "Coniston" },
  CSS: { name: "Cross Hands" },
  CSW: { name: "Colsterworth" },
  CTH: { name: "Crathie Bridge" },
  CTK: { name: "Catterick" },
  CTP: { name: "Clows Top" },
  CU2: { name: "Clunbury Hill" },
  CUL: { name: "Cullompton" },
  CUN: { name: "Clun" },
  CUP: { name: "Cupar" },
  CUR: { name: "Currock Hill" },
  CVN: { name: "Craven Arms" },
  CWA: { name: "Chipping Warden" },
  CWC: { name: "Crowcombe Court" },
  CWE: { name: "Crewe East" },
  CWN: { name: "Corwen" },
  CWS: { name: "Cwmbran SW" },
  CWT: { name: "Chatsworth" },
  CWV: { name: "Carsington Water Visitors Centre" },
  CWW: { name: "Conwy W" },
  CWY: { name: "Conwy S" },
  DAL: { name: "Dallachy" },
  DAM: { name: "Dalmally" },
  DAN: { name: "Danby" },
  DAR: { name: "Darlington" },
  DAW: { name: "Darwell" },
  DBN: { name: "Dunblane" },
  DBR: { name: "Devil's Bridge" },
  DBY: { name: "Diddlebury" },
  DCT: { name: "Didcot Rail Bridge" },
  DCW: { name: "Didcot West" },
  DDK: { name: "Devil's Dyke" },
  DEA: { name: "Deal" },
  DED: { name: "Deddington" },
  DEN: { name: "Denbigh" },
  DEP: { name: "Depden Water Tower" },
  DER: { name: "Derwent" },
  DET: { name: "Detling" },
  DEV: { name: "Devizes" },
  DFF: { name: "Duffield" },
  DFU: { name: "Dalton-in-Furness" },
  DIN: { name: "Dingwall" },
  DIS: { name: "Diss" },
  DIT: { name: "Ditchlingbeacon" },
  DKD: { name: "Dunkeld" },
  DKY: { name: "Dunkery Beacon" },
  DLB: { name: "Dale Bridge" },
  DLS: { name: "Dallas" },
  DLT: { name: "Dalston" },
  DMN: { name: "Duntulm N" },
  DNB: { name: "Dunbar SE" },
  DNE: { name: "Durham Northeast" },
  DNG: { name: "Dunning" },
  DNN: { name: "Dunoon" },
  DNT: { name: "Duntulm" },
  DNW: { name: "Doncaster Northwest" },
  DOC: { name: "Docking" },
  DOG: { name: "Dolgellau" },
  DOL: { name: "Dollar" },
  DON: { name: "Doncaster" },
  DOR: { name: "Dorchester" },
  DOU: { name: "Doune" },
  DOV: { name: "Dover Marina" },
  DOW: { name: "Downham Market" },
  DRB: { name: "Droma Bridge" },
  DRI: { name: "Driffield" },
  DRL: { name: "Darlton" },
  DRO: { name: "Droitwich" },
  DRS: { name: "Denbigh Ridge S" },
  DRU: { name: "Drumshade" },
  DSE: { name: "Daventry SE" },
  DSW: { name: "Dursley SW" },
  DTN: { name: "Donington" },
  DUB: { name: "Dulnain Bridge" },
  DUC: { name: "Duncton" },
  DUF: { name: "Dufftown" },
  DUL: { name: "Dulverton" },
  DUM: { name: "Dumfries" },
  DUN: { name: "Dunstable Airfield" },
  DUR: { name: "Durham" },
  DUS: { name: "Duns" },
  DUT: { name: "Dufton" },
  DUY: { name: "Dursley NW" },
  DVN: { name: "Daventry N" },
  DWI: { name: "Dalwhinnie" },
  DYN: { name: "Danbury N" },
  DYS: { name: "Dyserth" },
  EAG: { name: "Eaglescott" },
  EAR: { name: "Earith" },
  EAS: { name: "Easterton" },
  EAT: { name: "Eastgate" },
  EAW: { name: "Eastwell" },
  ECN: { name: "Eckford N" },
  EDG: { name: "Edgehill" },
  EDW: { name: "Edgehill West" },
  EDZ: { name: "Edzell" },
  EGG: { name: "Eggesford N" },
  ELK: { name: "Elkstone S" },
  ELL: { name: "Ellesmere" },
  ELM: { name: "Elmswell W" },
  ELT: { name: "East Linton" },
  ELV: { name: "Elvanfoot" },
  ELY: { name: "Ely" },
  ENS: { name: "Enstone" },
  ENW: { name: "Eastbourne NW" },
  ETC: { name: "Etchingham" },
  ETL: { name: "Etal" },
  ETT: { name: "Ettington" },
  EVE: { name: "Evesham" },
  EWW: { name: "Ennerdale Water W" },
  EYE: { name: "Eyebrook" },
  FAK: { name: "Fakenham" },
  FAL: { name: "Falgunzeon" },
  FAR: { name: "Faringdon" },
  FAV: { name: "Faversham" },
  FAW: { name: "Falkirk West" },
  FBG: { name: "Fraserburgh" },
  FBR: { name: "Fontburn Reservoir" },
  FE1: { name: "Feshie Airstrip" },
  FE2: { name: "Feshie Start N" },
  FE3: { name: "Feshie Descent Point" },
  FE5: { name: "Feshie S" },
  FEA: { name: "Fearnan" },
  FEN: { name: "Fenny Compton" },
  FER: { name: "Ferness" },
  FES: { name: "Feshiebridge" },
  FET: { name: "Fettercairn" },
  FEX: { name: "Felixstowe Pier" },
  FFD: { name: "Farnsfield" },
  FFI: { name: "Fforest Inn" },
  FFR: { name: "Forfar" },
  FHI: { name: "Fan Hir" },
  FHP: { name: "Fownhope" },
  FIB: { name: "Firle Beacon" },
  FIL: { name: "Filey" },
  FIM: { name: "Finmere" },
  FIN: { name: "Finavon" },
  FIS: { name: "Fishguard" },
  FLA: { name: "Flamborough" },
  FMA: { name: "Four Marks" },
  FNE: { name: "Fort William NE" },
  FNW: { name: "Falmouth NW" },
  FOA: { name: "Fort Augustus" },
  FOD: { name: "Fordoun" },
  FOL: { name: "Folkestone" },
  FON: { name: "Fontwell Park Roundabout" },
  FOR: { name: "Fordingbridge" },
  FOS: { name: "Foston" },
  FOV: { name: "Fovant" },
  FRE: { name: "Freuchie" },
  FRI: { name: "Fridaythorpe" },
  FRO: { name: "Frome" },
  FRW: { name: "Framlingham" },
  FTW: { name: "Fort William" },
  GA2: { name: "Gainsborough Power Station" },
  GAA: { name: "Galashiels" },
  GAB: { name: "Garboldisham" },
  GAF: { name: "Garforth" },
  GAG: { name: "Gargrave West" },
  GAI: { name: "Gainsborough" },
  GAL: { name: "Gallowfauld" },
  GAR: { name: "Garten" },
  GAT: { name: "Gateshead East" },
  GAY: { name: "Gaydon" },
  GBB: { name: "Gribbin Head" },
  GBE: { name: "Great Bedwyn" },
  GBR: { name: "Glasbury Bridge" },
  GCB: { name: "Gloucester Canal Bridge" },
  GDB: { name: "Glen Dee Bridge" },
  GDE: { name: "Glyndebourne" },
  GDF: { name: "Great Dun Fell" },
  GDN: { name: "Gordon" },
  GES: { name: "Gretna Services" },
  GFD: { name: "Glenfiddich Lodge" },
  GFG: { name: "Glenfarg Reservoir E" },
  GFL: { name: "Glen Falloch" },
  GHD: { name: "Garsdale Head" },
  GIF: { name: "Gifford" },
  GIL: { name: "Gillingham" },
  GIO: { name: "Giosla" },
  GIS: { name: "Gisburn" },
  GLA: { name: "Glastonbury" },
  GLB: { name: "Gelt Bridge" },
  GLD: { name: "Gilsland Village" },
  GLE: { name: "Glendevon" },
  GLF: { name: "Glenforsa" },
  GLN: { name: "Gleneagles" },
  GLS: { name: "Gloucester South" },
  GLT: { name: "Glenlatterach Dam N" },
  GLY: { name: "Gairlochy" },
  GNS: { name: "Grains" },
  GO2: { name: "Goole N" },
  GOO: { name: "Goole NE" },
  GOR: { name: "Goring" },
  GPN: { name: "Great Ponton" },
  GR1: { name: "Gransden NW" },
  GRA: { name: "Grantham" },
  GRC: { name: "Grasmere Church" },
  GRF: { name: "Great Ashfield" },
  GRI: { name: "Grimwith Reservoir" },
  GRL: { name: "Gransden Lodge" },
  GRM: { name: "Great Malvern" },
  GRN: { name: "Greenlaw" },
  GRO: { name: "Grosmont" },
  GRS: { name: "Grassington" },
  GRT: { name: "Great Rundale Tarn" },
  GRW: { name: "Grafham Water" },
  GSE: { name: "Grantshouse" },
  GSS: { name: "Glassonby" },
  GTN: { name: "Grantown" },
  GTO: { name: "Great Orme" },
  GTW: { name: "Great Witley" },
  GUI: { name: "Guisborough" },
  GUW: { name: "Guisborough SW" },
  GVE: { name: "Garve" },
  GWD: { name: "Goodwood Grandstand" },
  GYS: { name: "Great Yarmouth S" },
  HA2: { name: "Halton West" },
  HAB: { name: "Hay Bluff" },
  HAD: { name: "Halesland" },
  HAE: { name: "Halesworth" },
  HAI: { name: "Hailsham" },
  HAK: { name: "Hawick" },
  HAL: { name: "Halton" },
  HAN: { name: "Harrogate North" },
  HAR: { name: "Harting" },
  HAS: { name: "Hastings" },
  HAT: { name: "Hatherleigh" },
  HAV: { name: "Haverhill" },
  HAW: { name: "Hawkhurst" },
  HAY: { name: "Hay-on-wye" },
  HB1: { name: "HB start west" },
  HB2: { name: "HB start north" },
  HB3: { name: "HB start east" },
  HB4: { name: "HB East" },
  HB5: { name: "HB control point east" },
  HB7: { name: "HB Finish West" },
  HBR: { name: "Haydon Bridge" },
  HCM: { name: "Hinderclay Meadows Air-Strip" },
  HDD: { name: "Haddington" },
  HDL: { name: "Helmsdale" },
  HDW: { name: "Hardwick" },
  HEC: { name: "Hereford Cathedral" },
  HEE: { name: "Heathfield E" },
  HEL: { name: "Helensburgh" },
  HER: { name: "Hereford Racecourse" },
  HES: { name: "Henstridge" },
  HEU: { name: "Heugh Head" },
  HEX: { name: "Hexham" },
  HGM: { name: "Highham" },
  HHL: { name: "Hembury Hill" },
  HI1: { name: "Hinton Start W" },
  HI2: { name: "Hinton Start N." },
  HIC: { name: "Hinckley" },
  HIN: { name: "Hinton in the Hedges" },
  HLH: { name: "Hunstanton Lighthouse" },
  HLM: { name: "Helmsley" },
  HLS: { name: "Harlech South" },
  HNN: { name: "Hungerford North" },
  HNT: { name: "Huntercombe" },
  HOL: { name: "Holsworthy" },
  HON: { name: "Honeybourne" },
  HOR: { name: "Horncastle" },
  HOT: { name: "Hesket Old Town" },
  HOW: { name: "Howden Dam" },
  HPY: { name: "Harpley" },
  HRM: { name: "Horam" },
  HRR: { name: "Harrietsham" },
  HRT: { name: "Hartside Top" },
  HSE: { name: "Hawes" },
  HSG: { name: "Hathersage" },
  HSM: { name: "Hornsea Mere" },
  HTN: { name: "Honington Airfield" },
  HTY: { name: "Huntly" },
  HUD: { name: "Hope Under Dinmore" },
  HUL: { name: "Hullavington M4/J17" },
  HUM: { name: "Humber Bridge" },
  HUN: { name: "Hungerford" },
  HUR: { name: "Hurstbourne Tarrant" },
  HUS: { name: "Husbands Bosworth" },
  HVS: { name: "Havant S" },
  HVT: { name: "Havant NW" },
  HVW: { name: "Haverfordwest" },
  HWB: { name: "Halfway Bridge" },
  HWH: { name: "Halfway House" },
  HWL: { name: "Haltwistle" },
  HYE: { name: "Hay East" },
  ILF: { name: "Ilfracombe" },
  ILS: { name: "Ilsley" },
  INC: { name: "Insch" },
  ING: { name: "Ingleton" },
  INK: { name: "Inchkinloch" },
  INV: { name: "Inverary" },
  IPE: { name: "Ipswich E" },
  ISE: { name: "Inverness SE" },
  ISL: { name: "Islip" },
  IVS: { name: "Invershin" },
  IVY: { name: "Ivybridge East" },
  IWE: { name: "Iwerne Minster" },
  JED: { name: "Jedburgh" },
  KCA: { name: "Kielder Castle" },
  KCG: { name: "Kincraig" },
  KDL: { name: "Kendal" },
  KEE: { name: "Keevil" },
  KEK: { name: "Keswick" },
  KEL: { name: "Kelso" },
  KEM: { name: "Kempock Point" },
  KEN: { name: "Kenley" },
  KES: { name: "Kettering South" },
  KEX: { name: "Kexby Bridge" },
  KGS: { name: "Kingsclere" },
  KIB: { name: "Kinbrace" },
  KIC: { name: "Kinclaven" },
  KID: { name: "Kidderminster" },
  KIE: { name: "Kielder Reservoir" },
  KIG: { name: "Kingussie" },
  KIK: { name: "Kirkharle" },
  KIL: { name: "Kilcreggan" },
  KIM: { name: "Kingham" },
  KIN: { name: "Kineton" },
  KIP: { name: "Kippen" },
  KIR: { name: "Kirton-in-lindsey" },
  KLE: { name: "Kellie Castle" },
  KLH: { name: "Kilham" },
  KLN: { name: "Killin" },
  KLO: { name: "Kirkby Lonsdale" },
  KLT: { name: "Kinlet" },
  KLY: { name: "King's Lynn" },
  KME: { name: "Kentmere" },
  KML: { name: "Kirkmichael" },
  KMR: { name: "Kenmore" },
  KNA: { name: "Knaresborough" },
  KNI: { name: "Knighton" },
  KNO: { name: "Knowstone" },
  KNW: { name: "Knighton West" },
  KRB: { name: "Kirkbymoorside" },
  KRM: { name: "Kirriemuir" },
  KSB: { name: "Kingston Bagpuize" },
  KST: { name: "Kirkby Stephen Station" },
  KTH: { name: "Keith" },
  KTN: { name: "Kilmington" },
  KWE: { name: "Kinlochewe" },
  KWK: { name: "Knightwick" },
  KWO: { name: "Kibworth" },
  KYL: { name: "Kyleakin" },
  LA1: { name: "Lasham Start Southeast" },
  LA2: { name: "Lasham Start East" },
  LA3: { name: "Lasham Church" },
  LA4: { name: "Lasham Start South" },
  LA5: { name: "Lasham West" },
  LA6: { name: "Lasham Start North" },
  LAD: { name: "Lauder" },
  LAE: { name: "Llanelli East" },
  LAG: { name: "Langport" },
  LAI: { name: "Lairg" },
  LAL: { name: "Lake Alaw Reservoir" },
  LAM: { name: "Lampeter" },
  LAN: { name: "Langham" },
  LAP: { name: "Lapford" },
  LAR: { name: "Lattrig" },
  LAS: { name: "Lasham Finish North" },
  LAT: { name: "Latheron" },
  LAU: { name: "Launceston" },
  LBD: { name: "Longbridge Deverill" },
  LBE: { name: "Loch Bradan E" },
  LBN: { name: "Lambourn" },
  LBR: { name: "Laggan Bridge" },
  LBU: { name: "Lochbuie" },
  LBZ: { name: "Leighton Buzzard NE" },
  LCE: { name: "Llyn Celyn NW" },
  LCH: { name: "Lanchester" },
  LCL: { name: "Lower Clopton" },
  LDB: { name: "Lochindorb Castle" },
  LDM: { name: "Laggan Dam" },
  LDN: { name: "Loddon" },
  LDR: { name: "Lindores" },
  LEA: { name: "Lochearnhead" },
  LEB: { name: "Lake Eiddew-bach" },
  LED: { name: "Ledbury" },
  LEH: { name: "Leadenham" },
  LEI: { name: "Leicester M1 Services" },
  LEK: { name: "Leck" },
  LEL: { name: "Loch Eil West" },
  LEN: { name: "Leicester North" },
  LEO: { name: "Leominster" },
  LER: { name: "Loch Errochty East" },
  LES: { name: "Leicester South" },
  LET: { name: "Leighterton" },
  LEW: { name: "Lewes North" },
  LEY: { name: "Leyburn" },
  LEZ: { name: "Leighton Buzzard" },
  LFC: { name: "Lindisfarne Castle" },
  LFN: { name: "Llanfyllin" },
  LGG: { name: "Loch Laggan North East" },
  LGI: { name: "Lochgilphead" },
  LGN: { name: "Loch Garry N" },
  LGO: { name: "Lochgoilhead" },
  LIS: { name: "Lismore" },
  LIT: { name: "Littleport" },
  LKD: { name: "Liskeard SE" },
  LLA: { name: "Llangollen" },
  LLB: { name: "Llanbadarn" },
  LLC: { name: "Llanfair Caereinion" },
  LLD: { name: "Llandovery" },
  LLE: { name: "Lleweni Parc" },
  LLG: { name: "Llangynidr Bridge" },
  LLI: { name: "Llanidloes" },
  LLM: { name: "Llanymynech" },
  LLN: { name: "Llanrwst" },
  LLO: { name: "Llandeilo" },
  LLS: { name: "Llantysilio" },
  LLT: { name: "Loch Lomond Tarbet" },
  LLW: { name: "Llandrindod Wells" },
  LMB: { name: "Lochmaben" },
  LMD: { name: "Loch Mullardoch East" },
  LMO: { name: "Loch Morlich" },
  LMR: { name: "Ledmore" },
  LMU: { name: "Loch Muick" },
  LMV: { name: "Long Marston Church" },
  LMW: { name: "Leominster NW" },
  LMY: { name: "Loch Moy" },
  LNE: { name: "Lichfield NE" },
  LOA: { name: "Lochailort" },
  LOC: { name: "Lockerbie" },
  LOD: { name: "Linn of Dee" },
  LOG: { name: "Loch Gairloch SE" },
  LOI: { name: "Loch Laidon Island" },
  LOK: { name: "Loch Kinord" },
  LOL: { name: "Loch Lochy North East" },
  LOM: { name: "Lake of Menteith" },
  LON: { name: "Longleat" },
  LOQ: { name: "Loch Quoich East" },
  LOU: { name: "Louth" },
  LOW: { name: "Lowick" },
  LRI: { name: "Little Rissington" },
  LRK: { name: "Lanark" },
  LSA: { name: "Llansannan" },
  LSL: { name: "Llandysul" },
  LSN: { name: "Loch Seilich N" },
  LSS: { name: "Liss" },
  LSU: { name: "Long Sutton" },
  LTF: { name: "Langtoft" },
  LTN: { name: "Longtown" },
  LUD: { name: "Ludlow" },
  LUN: { name: "Luncarty" },
  LUS: { name: "Lussa Loch S" },
  LUT: { name: "Lutterworth" },
  LVE: { name: "Loch Venachar" },
  LVN: { name: "Lavenham" },
  LWL: { name: "Low Lorton" },
  LWN: { name: "Lewes nw" },
  LYB: { name: "Llwyngwril Bridge" },
  LYD: { name: "Leyland North East" },
  LYN: { name: "Lyneham a/f" },
  LYR: { name: "Ladybower Reservoir" },
  LYV: { name: "Lyveden" },
  MAC: { name: "Machynlleth Station" },
  MAD: { name: "Market Deeping" },
  MAE: { name: "Marlborough E" },
  MAH: { name: "Market Harborough" },
  MAI: { name: "Maidstone East" },
  MAL: { name: "Malton" },
  MAM: { name: "Malmesbury" },
  MAN: { name: "Manton" },
  MAR: { name: "Marlborough" },
  MAS: { name: "Masham" },
  MAT: { name: "Matlock" },
  MAW: { name: "Market Weighton" },
  MBL: { name: "Mablethorpe" },
  MBO: { name: "Market Bosworth" },
  MBR: { name: "Montford Bridge" },
  MBU: { name: "Melbury Bubb" },
  MBY: { name: "Manby" },
  MCH: { name: "March" },
  MDN: { name: "Maidstone North" },
  MEA: { name: "Measham" },
  MEE: { name: "East Meon" },
  MEL: { name: "Melksham" },
  MEM: { name: "Membury" },
  MEN: { name: "Mendlesham" },
  MER: { name: "Mere" },
  MET: { name: "Melton Mowbray" },
  MEW: { name: "West Meon Hut" },
  MEX: { name: "Mexborough S" },
  MFD: { name: "Mansfield NE" },
  MGH: { name: "Margery Hill" },
  MHT: { name: "Minchinhampton" },
  MIC: { name: "Micheldever" },
  MIG: { name: "Mingary Pier" },
  MIL: { name: "Milfield" },
  MIM: { name: "Midhurst Mast" },
  MIN: { name: "Mintlaw" },
  MIT: { name: "Milnthorpe" },
  MIW: { name: "Midhurst West" },
  MLL: { name: "Mellon Charles" },
  MLM: { name: "Melmerby" },
  MLN: { name: "Molton" },
  MLT: { name: "Milton" },
  MLY: { name: "Madley" },
  MNE: { name: "Maryport NE" },
  MNS: { name: "Menai Strait" },
  MNW: { name: "Millom NW" },
  MOK: { name: "Monkton" },
  MOM: { name: "Monmouth" },
  MON: { name: "Montgomery" },
  MOO: { name: "Muir of Ord" },
  MOP: { name: "Morpeth" },
  MOR: { name: "Moreton-in-marsh" },
  MOS: { name: "Mossat" },
  MOT: { name: "Mortimer Church" },
  MOU: { name: "Moulton Church" },
  MOY: { name: "Moy Lodge" },
  MRE: { name: "Margate E" },
  MRN: { name: "Market Rasen" },
  MRY: { name: "Maryport" },
  MSE: { name: "Mansfield SE" },
  MTD: { name: "Methwold" },
  MTF: { name: "Mottisfont Station" },
  MTH: { name: "Moota Hill" },
  MTM: { name: "Melton Mast" },
  MTR: { name: "Montrose" },
  MUD: { name: "Mudford Gate" },
  MUM: { name: "Mumbles Head" },
  MUN: { name: "Mundford" },
  MUR: { name: "Mursley" },
  MUT: { name: "Murton" },
  MVN: { name: "Methven" },
  MWD: { name: "Mallwyd" },
  MWP: { name: "Middle Wallop" },
  MY2: { name: "Mynd S" },
  MY3: { name: "Mynd N" },
  MYN: { name: "Mynd" },
  MZI: { name: "Monzie" },
  NAB: { name: "New Abbey" },
  NAE: { name: "Naseby East" },
  NAI: { name: "Nailsworth" },
  NAN: { name: "Narberth N" },
  NAW: { name: "Naseby West" },
  NBR: { name: "Norham Bridge" },
  NCH: { name: "Newchurch" },
  NDL: { name: "Needles" },
  NDU: { name: "North Duffield" },
  NEA: { name: "Northleach East" },
  NEC: { name: "New Cumnock" },
  NED: { name: "New Deer" },
  NEE: { name: "Needham Market E" },
  NEF: { name: "Nefyn" },
  NEG: { name: "New Galloway" },
  NEM: { name: "Newmill" },
  NEN: { name: "Newbury N" },
  NES: { name: "Newbury South" },
  NET: { name: "Newtown" },
  NEW: { name: "Newbury Racecourse" },
  NH2: { name: "North Hill N" },
  NHL: { name: "North Hill" },
  NLE: { name: "Northleach" },
  NMT: { name: "Newmarket" },
  NOC: { name: "Newcastle on Clun" },
  NOR: { name: "Norman Cross" },
  NOS: { name: "Northampton South" },
  NOW: { name: "Northampton West" },
  NPT: { name: "Newport Pagnall" },
  NRA: { name: "Nunraw Abbey" },
  NRT: { name: "Northallerton" },
  NST: { name: "Newton Stewart" },
  NTA: { name: "N Tawton" },
  NTB: { name: "Nethybridge" },
  NTN: { name: "Neenton" },
  NUN: { name: "Nunney" },
  NWK: { name: "Newark" },
  NWT: { name: "Newent" },
  NY1: { name: "Nympsfield Finish East" },
  NY2: { name: "Nympsfield Finish West" },
  NYM: { name: "Nympsfield" },
  OAE: { name: "Oakham E" },
  OAK: { name: "Oakington" },
  OBA: { name: "Oban Airfield" },
  OBN: { name: "Oban Station" },
  ODI: { name: "Odiham" },
  OGB: { name: "Ogbourne" },
  OKE: { name: "Okehampton East" },
  OLL: { name: "Ollerton" },
  OLN: { name: "Olney" },
  ORA: { name: "Old Radnor" },
  OSB: { name: "Osbournby" },
  OSW: { name: "Oswestry" },
  OTM: { name: "Ottercops Moss" },
  OUN: { name: "Oundle" },
  OUS: { name: "Ousby E" },
  OVE: { name: "Overton" },
  OXF: { name: "Oxford East" },
  OXM: { name: "Oxford M40 Services" },
  OXN: { name: "Oxford North" },
  OXS: { name: "Oxford South" },
  OXT: { name: "Oxton" },
  PA2: { name: "Pateley SE" },
  PAD: { name: "Paddock Wood" },
  PAN: { name: "Pangbourne" },
  PAP: { name: "Papworth" },
  PAR: { name: "Parham" },
  PAT: { name: "Pateley Bridge" },
  PCM: { name: "Pencombe" },
  PCN: { name: "Porthcawl North" },
  PCS: { name: "Portmoak Caravan Site" },
  PCT: { name: "Pontefract" },
  PEB: { name: "Porthmadog East Bridge" },
  PEE: { name: "Peebles" },
  PEI: { name: "Penrith" },
  PEM: { name: "Pembroke Dock" },
  PEN: { name: "Pendock" },
  PET: { name: "Peterborough" },
  PEV: { name: "Peveril Castle" },
  PEW: { name: "Pewsey" },
  PGO: { name: "Pitsligo" },
  PIC: { name: "Pickenham" },
  PIE: { name: "Penrith East" },
  PIT: { name: "Pitsford" },
  PKG: { name: "Pickering" },
  PLE: { name: "Peterlee" },
  PLM: { name: "Plumpton" },
  PLU: { name: "Pluckley" },
  PLY: { name: "Pitlochry" },
  PNS: { name: "Pontsticill Reservoir" },
  PNT: { name: "Portsmouth N" },
  PNW: { name: "Parham NW" },
  PO1: { name: "Portmoak NW" },
  PO2: { name: "Portmoak W" },
  POA: { name: "Potarch Bridge" },
  POC: { name: "Pocklington" },
  POF: { name: "Pontypool Folly" },
  POH: { name: "Pontesbury Hill" },
  POL: { name: "Polegate" },
  POP: { name: "Popham" },
  POR: { name: "Portmoak Clubhouse" },
  POS: { name: "Pocklington South" },
  POT: { name: "Potton" },
  POW: { name: "Powburn" },
  PPE: { name: "Pontypool E" },
  PPN: { name: "Pontypool N" },
  PPP: { name: "Port Appin" },
  PR1: { name: "Park Control Point E" },
  PRE: { name: "Presteigne" },
  PRI: { name: "Prince's Risborough" },
  PRK: { name: "Park-the" },
  PRN: { name: "Preston North" },
  PRT: { name: "Portree" },
  PSE: { name: "Pershore se" },
  PSH: { name: "Portesham" },
  PTD: { name: "Pontardulais" },
  PTE: { name: "Port Eynon" },
  PTF: { name: "Petersfield South" },
  PTH: { name: "Perth" },
  PTM: { name: "Porthmadog" },
  PTN: { name: "Pirton" },
  PTR: { name: "Portsmouth Tower" },
  PTW: { name: "Petersfield West" },
  PVY: { name: "Pevensey" },
  PWN: { name: "Penwhirn Reservoir" },
  PWW: { name: "Pwllheli West" },
  PYE: { name: "Plymouth E" },
  PYF: { name: "Pen-y-Fan" },
  PYS: { name: "Prestatyn S" },
  PYW: { name: "Plymouth W" },
  RAB: { name: "Ramsbury" },
  RAD: { name: "Radstock" },
  RAG: { name: "Raglan" },
  RAM: { name: "Ramsey" },
  RAN: { name: "Rannoch Station" },
  RAR: { name: "Ravensthorpe Reservoir" },
  RAV: { name: "Ravenglass N" },
  RBR: { name: "Roybridge" },
  RBS: { name: "Rosebush" },
  RBY: { name: "Rothbury" },
  RDN: { name: "Rattlesden A/F Centre" },
  RDW: { name: "Radway" },
  REA: { name: "Reading West" },
  REE: { name: "Reedham" },
  RET: { name: "Retford" },
  RHD: { name: "Rattray Head" },
  RHI: { name: "Rhigos" },
  RHO: { name: "Rhossdhu House" },
  RHU: { name: "Rhuddlan" },
  RHY: { name: "Rhayader" },
  RI2: { name: "Rivar Hill North" },
  RIC: { name: "Richmond" },
  RID: { name: "Ridgewell Church" },
  RIN: { name: "Ringmer" },
  RIP: { name: "Ripon" },
  RIV: { name: "Rivar Hill" },
  RIW: { name: "Ridgewell Field" },
  RKB: { name: "Rockbourne" },
  RNE: { name: "Rugby Northeast" },
  RNI: { name: "Rhynie" },
  ROA: { name: "Roadford" },
  ROC: { name: "Rochester" },
  ROD: { name: "Rodney's Pillar" },
  ROH: { name: "Rothes" },
  ROS: { name: "Ross-on-wye" },
  ROT: { name: "Rotherham" },
  ROY: { name: "Royston" },
  RSE: { name: "Redruth SE" },
  RSN: { name: "Rosneath" },
  RSY: { name: "Rothesay" },
  RTH: { name: "Rosthwaite" },
  RU1: { name: "Rufforth South" },
  RUB: { name: "Rubha Reidh" },
  RUF: { name: "Rufforth" },
  RUG: { name: "Rugby" },
  RUN: { name: "Ruthin NE" },
  RUS: { name: "Rushden" },
  RUW: { name: "Ruthin West" },
  RVN: { name: "Ruthven" },
  RWD: { name: "Rutland Water Dam" },
  RYB: { name: "Rydal Bridge" },
  RYD: { name: "Ryde" },
  RYE: { name: "Rye" },
  SAC: { name: "Sackville" },
  SAL: { name: "Salisbury Cathedral" },
  SAN: { name: "Sandhill Farm" },
  SAP: { name: "Shap" },
  SAR: { name: "Sarnesfield" },
  SAS: { name: "Salisbury South" },
  SAW: { name: "Sandwich" },
  SAX: { name: "Saxthorpe" },
  SB2: { name: "Saltby NW" },
  SBB: { name: "Strubby" },
  SBR: { name: "Santon Bridge" },
  SBT: { name: "Simonsbath" },
  SBY: { name: "Saltby" },
  SCB: { name: "Scarborough" },
  SCF: { name: "Scalford Church" },
  SCL: { name: "Scoulton" },
  SCN: { name: "Strathcarron" },
  SCO: { name: "Scourie" },
  SCP: { name: "St Catherine's Point" },
  SCU: { name: "Scunthorpe N" },
  SDV: { name: "St Davids" },
  SDW: { name: "Seighford South-West" },
  SE2: { name: "Seighford Hangar" },
  SEA: { name: "Seaford East" },
  SED: { name: "Sedbergh" },
  SEL: { name: "Selset Reservoir" },
  SEN: { name: "Sennybridge" },
  SET: { name: "Settle" },
  SEV: { name: "Severn Bridge N" },
  SEW: { name: "Sheffield West" },
  SFB: { name: "Stamford Bridge" },
  SFD: { name: "Sleaford" },
  SFE: { name: "Sheffield East" },
  SFW: { name: "Stratford West" },
  SGW: { name: "Stelling Windmill" },
  SH2: { name: "Shobdon NW" },
  SH3: { name: "Shobdon E" },
  SH4: { name: "Shobdon West" },
  SHA: { name: "Shaftesbury" },
  SHB: { name: "Sherborne" },
  SHD: { name: "Stoer Head" },
  SHE: { name: "Sheffield North" },
  SHI: { name: "Shirebrook Station" },
  SHL: { name: "Salt Hill Mast" },
  SHM: { name: "Shepton Mallett" },
  SHO: { name: "Shobdon" },
  SHP: { name: "Shipston-on-stour" },
  SHS: { name: "Shrewsbury" },
  SHT: { name: "Shottaton" },
  SHV: { name: "Shrivenham N" },
  SHW: { name: "Shrewsbury NW" },
  SHY: { name: "Shawbury" },
  SID: { name: "Sidmouth" },
  SIL: { name: "Silverstone" },
  SIS: { name: "Stirling South" },
  SIT: { name: "Sittingbourne" },
  SIW: { name: "Stirling Northwest" },
  SIX: { name: "Sixpenny Handley" },
  SKB: { name: "Stickney Bridge" },
  SKE: { name: "Skeffington" },
  SKS: { name: "Stocks Reservoir South West" },
  SKW: { name: "Selkirk W" },
  SLE: { name: "Sleap" },
  SLL: { name: "Silloth" },
  SLS: { name: "Selsey Bill" },
  SMA: { name: "Smailholm Tower" },
  SMB: { name: "Six Mile Bottom" },
  SML: { name: "St Mary's Loch" },
  SMM: { name: "St Michael's Mount" },
  SN2: { name: "Snitterfield SW" },
  SNA: { name: "Snainton" },
  SNI: { name: "Snitterfield" },
  SNO: { name: "Swindon N" },
  SNP: { name: "Staindrop" },
  SNS: { name: "St Neots S" },
  SNW: { name: "Stratford NW" },
  SOA: { name: "Stratford" },
  SOF: { name: "Sutton-on-forest" },
  SOH: { name: "Soham" },
  SOS: { name: "Stokenchurch South" },
  SOU: { name: "Southam" },
  SOW: { name: "Stow" },
  SPA: { name: "Spalding" },
  SPB: { name: "Sharperton Bridge" },
  SPD: { name: "Spey Dam" },
  SPE: { name: "Spean Bridge" },
  SPH: { name: "Staplehurst" },
  SPI: { name: "Spilsby" },
  SPL: { name: "Spittal of Glenshee" },
  SPN: { name: "Spinningdale Bridge" },
  SPP: { name: "Sheppey E" },
  SPS: { name: "Shap S" },
  SPT: { name: "Shipton" },
  SPU: { name: "Spurn Head North" },
  SRE: { name: "Stroud E" },
  SRN: { name: "Strontian" },
  SRR: { name: "Storrington SW" },
  SSO: { name: "Sheffield South" },
  SSW: { name: "Stoke SW" },
  STA: { name: "Stafford" },
  STB: { name: "St Boswells" },
  STC: { name: "Stokenchurch Tower" },
  STD: { name: "Stradishall" },
  STE: { name: "Steyning" },
  STF: { name: "St Fillans" },
  STH: { name: "Stanhope" },
  STI: { name: "Stirling" },
  STK: { name: "Stockbridge" },
  STN: { name: "St Neots" },
  STO: { name: "Stone" },
  STP: { name: "Stourport" },
  STR: { name: "Strachan" },
  STS: { name: "Stony Stratford" },
  STT: { name: "Stretton" },
  STU: { name: "Sturminster Newton" },
  STW: { name: "Stow-on-the-wold" },
  SU1: { name: "Sutton Bank Start S" },
  SU2: { name: "Sutton Bank Start W" },
  SU3: { name: "Sutton Bank Control Point N" },
  SU4: { name: "Sutton Bank Control Point S" },
  SUD: { name: "Sudbury" },
  SUT: { name: "Sutton Bank" },
  SUW: { name: "Shipton under Wychwood" },
  SVN: { name: "Strathaven" },
  SWD: { name: "Snowdon" },
  SWE: { name: "Swindon East" },
  SWH: { name: "Shawhead" },
  SWL: { name: "Swalcliffe" },
  SWM: { name: "Southwell Minster" },
  SWS: { name: "Swindon South" },
  SWT: { name: "Swainsthorpe" },
  SWW: { name: "Swindon W" },
  SXB: { name: "Saxby Church" },
  SYB: { name: "Syre Bridge" },
  TA1: { name: "Talgarth NW" },
  TA2: { name: "Talgarth W" },
  TA3: { name: "Talgarth S" },
  TAD: { name: "Tarland" },
  TAL: { name: "Talgarth" },
  TAR: { name: "Tarbert" },
  TAU: { name: "Taunton" },
  TAV: { name: "Tavistock" },
  TB1: { name: "Tibenham Start SE" },
  TBK: { name: "Troutbeck" },
  TBN: { name: "Tetbury North" },
  TBS: { name: "Tetbury South" },
  TBW: { name: "Tetbury West" },
  TBY: { name: "Tenby" },
  TCM: { name: "The Camp" },
  TDL: { name: "Tindale" },
  TEB: { name: "Tebay" },
  TED: { name: "Tenterden" },
  TEE: { name: "Telford East" },
  TEG: { name: "Temple Guiting" },
  TEL: { name: "Telford" },
  TEN: { name: "Tenbury Wells" },
  TES: { name: "Telford South" },
  TEV: { name: "Teviothead" },
  TEW: { name: "Tewkesbury North" },
  TFS: { name: "Tarfside" },
  THA: { name: "Thame Church" },
  THD: { name: "Todhead" },
  THE: { name: "Thetford" },
  THG: { name: "Thorngumbald" },
  THI: { name: "Thirsk" },
  THM: { name: "Thame Rail Bridge" },
  THN: { name: "Thornhill" },
  THO: { name: "Thornton" },
  THP: { name: "Thrapston" },
  TIA: { name: "Tintern Abbey" },
  TIB: { name: "Tibenham" },
  TIC: { name: "Tickhill" },
  TID: { name: "Tideswell Church" },
  TIE: { name: "Tiverton East" },
  TIN: { name: "Tomatin" },
  TIP: { name: "Tiptree" },
  TIS: { name: "Tisbury" },
  TIV: { name: "Tiverton" },
  TNE: { name: "Thornbury Northeast" },
  TNW: { name: "Telford NW" },
  TOC: { name: "Tockwith" },
  TOD: { name: "Toddington" },
  TOG: { name: "Tongue" },
  TOK: { name: "Torksey Viaduct" },
  TOM: { name: "Tomintoul" },
  TON: { name: "Tontine Inn" },
  TOR: { name: "Torver" },
  TOW: { name: "Towcester" },
  TRE: { name: "Tregaron" },
  TRF: { name: "Turriff" },
  TRN: { name: "Thorne" },
  TRO: { name: "Trowbridge" },
  TRR: { name: "Truro NE" },
  TRU: { name: "Truleigh" },
  TRW: { name: "Truro West" },
  TRY: { name: "Treyford" },
  TSW: { name: "Telford SW" },
  TUJ: { name: "Tuxford Rail Junction" },
  TUL: { name: "Tulla Loch East" },
  TUM: { name: "Tummel Bridge" },
  TUW: { name: "Tulla Loch West" },
  ULL: { name: "Ullswater" },
  ULP: { name: "Ulpha" },
  ULV: { name: "Ulverston" },
  UPA: { name: "Upavon Hangar W" },
  UPL: { name: "Ullapool" },
  UPP: { name: "Uppingham N" },
  UPS: { name: "Upper Sapey" },
  UPW: { name: "Upwood Hangar" },
  USK: { name: "Usk" },
  UTT: { name: "Uttoxeter" },
  UWH: { name: "Uffington White Horse" },
  VRY: { name: "Vyrnwy" },
  WAB: { name: "Waterbeck" },
  WAL: { name: "Walford" },
  WAN: { name: "Wantage" },
  WAO: { name: "Watton" },
  WAR: { name: "Warcop" },
  WAS: { name: "Washington" },
  WAT: { name: "Watford Gap" },
  WAW: { name: "Watch Water Reservoir" },
  WBN: { name: "Whiteburn" },
  WBR: { name: "Weldon Bridge" },
  WBS: { name: "Wetherby South" },
  WBY: { name: "Whitby Bridge" },
  WCB: { name: "Winchcombe" },
  WCH: { name: "Woodchurch Farm" },
  WDD: { name: "Widdrington Station" },
  WDG: { name: "Witheridge" },
  WDM: { name: "Windermere" },
  WEB: { name: "Westbury NE" },
  WEC: { name: "Westcott" },
  WEG: { name: "Wellington" },
  WEL: { name: "Welford" },
  WEN: { name: "Wendling" },
  WES: { name: "Westbury" },
  WET: { name: "Wetherby" },
  WEY: { name: "Weymouth" },
  WFN: { name: "Whitfield North" },
  WGT: { name: "Wigton" },
  WGW: { name: "Wing W" },
  WH2: { name: "Whitchurch Hants" },
  WHD: { name: "Whiddon Down" },
  WHI: { name: "Whitchurch Shropshire" },
  WHM: { name: "Whitehaven Marina" },
  WHN: { name: "Whittington" },
  WHR: { name: "Whiteadder Reservoir" },
  WHT: { name: "Whitstable" },
  WHW: { name: "Whitchurch Shropshire West" },
  WIC: { name: "Whickham" },
  WIG: { name: "Wingham" },
  WIK: { name: "Wick West" },
  WIM: { name: "Wimbleball" },
  WIN: { name: "Wincanton" },
  WIS: { name: "Wisbech" },
  WIW: { name: "Wilton West" },
  WKB: { name: "Warkworth Bridge" },
  WKE: { name: "Worksop East" },
  WKW: { name: "Wickwar" },
  WLD: { name: "West Lomond Hill" },
  WLL: { name: "Willersley" },
  WLS: { name: "Wells" },
  WLT: { name: "Waternish Point" },
  WLW: { name: "Worlingworth" },
  WLY: { name: "Woolley Down" },
  WME: { name: "Wormingford East" },
  WML: { name: "Wormelow" },
  WMW: { name: "Wormingford West" },
  WNE: { name: "Welshpool NE" },
  WNT: { name: "Westnewton" },
  WNW: { name: "Wantage Northwest" },
  WO2: { name: "Weston Finish Point" },
  WOB: { name: "Woburn Abbey" },
  WOC: { name: "Worcester Racecourse" },
  WOD: { name: "Woodall Services" },
  WOE: { name: "Woore" },
  WOG: { name: "Weston-on-the-green" },
  WOL: { name: "Wooler East" },
  WOM: { name: "Woburn" },
  WON: { name: "Walton on Naze Pier" },
  WOO: { name: "Wooler" },
  WOR: { name: "Worcester" },
  WPL: { name: "Withypool" },
  WPR: { name: "Wistlandpound Reservoir" },
  WRA: { name: "Wragby" },
  WRK: { name: "Workington" },
  WRM: { name: "Wormingford" },
  WRO: { name: "Wroughton" },
  WSG: { name: "Wimborne St Giles" },
  WSL: { name: "Winslow" },
  WSM: { name: "Wattisham" },
  WSP: { name: "Worksop" },
  WTB: { name: "Waterbeach N" },
  WTH: { name: "Worthing" },
  WTM: { name: "Worthen" },
  WTN: { name: "Watlington" },
  WWE: { name: "Wast Water E" },
  WWW: { name: "Wast Water W" },
  WYL: { name: "Wylye" },
  WYM: { name: "Wymondham" },
  YAT: { name: "Yate" },
  YEO: { name: "Yeovil Reservoir" },
  YET: { name: "Yetholm" },
  YOE: { name: "York East" },
  YOR: { name: "York" },
  YTN: { name: "Yeovilton" },
  YTT: { name: "Yattendon" },
};

export default TURNPOINTS;
