const TURNPOINTS: Record<string, string> = {
  AB1: "Aboyne Bridge",
  ABA: "Abbey St Bathans",
  ABB: "Abbot's Bromley",
  ABD: "Aboyne Dinnet",
  ABE: "Abergavenny",
  ABF: "Aberfeldy",
  ABG: "Abingdon Airfield",
  ABI: "Abington",
  ABL: "Aberfoyle",
  ABN: "Abingdon Bridge",
  ABO: "Aboyne",
  ABP: "Ashburnham",
  ABR: "Aberchirder",
  ABS: "Abergavenny SW",
  ABY: "Aberystwyth Pier",
  ACB: "Alconbury",
  ACC: "Accrington NE",
  ACH: "Achnasheen",
  ACN: "Achnabourin",
  AD1: "Aston Down Finish N",
  AD2: "Aston Down Finish S",
  ADE: "Aberdare SE",
  ADF: "Andoversford",
  ADN: "Aberdaron",
  AFB: "Alfriston Bridge",
  AFD: "Alford",
  AGS: "Abergele South",
  AHA: "Altnaharra",
  AKE: "Alnwick E",
  ALB: "Aln Bridge",
  ALC: "Alcester",
  ALE: "Aylesham",
  ALF: "Alfreton",
  ALL: "Allendale Bridge",
  ALM: "Alnwick Moor SW",
  ALO: "Alston",
  ALR: "Aberlour",
  ALS: "Alfreton South",
  ALV: "Alva",
  ALW: "Alton Southwest",
  ALY: "Alyth",
  AMB: "Amberley",
  AMS: "Ambleside",
  AMU: "Amulree",
  AND: "Andover SW",
  ANE: "Andover SE",
  ANX: "Ansty Cross",
  APP: "Appleby",
  ARD: "Ardvasar",
  ARL: "Ardrishaig Lighthouse",
  ARU: "Arundel",
  ASB: "Ashbury",
  ASE: "Ashford East",
  ASH: "Ashbourne",
  ASP: "Aspatria",
  ASS: "Ashford South",
  AST: "Aston Down",
  ASW: "Airdrie Southwest",
  ASY: "Ashley",
  ATH: "Atherstone",
  ATT: "Attleborough",
  ATW: "Alton Towers",
  AUL: "Auldgirth",
  AVE: "Avebury",
  AVN: "Avening",
  AXM: "Axminster",
  AYL: "Aylesbury",
  AYS: "Aysgarth",
  BA1: "Banbury W",
  BA2: "Banbury N",
  BAA: "Balallan",
  BAB: "Ballachulish Bridge",
  BAC: "Backwater Reservoir",
  BAD: "Badminton",
  BAE: "Bath East",
  BAF: "Balfron",
  BAG: "Bangor-on-Dee",
  BAH: "Barrhill",
  BAK: "Bakewell",
  BAL: "Bala",
  BAM: "Bampton",
  BAN: "Banbury",
  BAR: "Barnard Castle",
  BAS: "Basingstoke",
  BAT: "Bath Racecourse SW",
  BAW: "Banchory West",
  BBG: "Boat O'Brig",
  BBK: "Bracken Bank",
  BBR: "Bath Bridge",
  BCA: "Bishop's Caundle",
  BCE: "Banchory East",
  BCL: "Bishop's Cleeve NW",
  BCN: "Brechin",
  BCS: "Bishops Castle",
  BCW: "Bishops Cleeve W",
  BCY: "Banchory",
  BDM: "Bodmin SE",
  BDN: "Beadnell Harbour",
  BDO: "Balado",
  BDW: "Bodelwyddan",
  BDY: "Bardney",
  BE2: "Beal",
  BEA: "Beaminster",
  BEC: "Beckington",
  BED: "Bedford Bridge",
  BEE: "Beer Head W",
  BEL: "Bellingham",
  BEM: "Bembridge",
  BEN: "Bentpath",
  BER: "Berwick W",
  BES: "St Bees Head",
  BET: "Beattock",
  BEU: "Beulah",
  BEV: "Beverley",
  BEW: "Bewl Water",
  BF1: "Booker Finish SW",
  BF2: "Booker Finish NW",
  BFD: "Belford",
  BFF: "Banff",
  BGA: "Biggar",
  BGG: "Brigg",
  BGO: "Bangor SE",
  BGR: "Blairgowrie",
  BGT: "Bedlands Gate",
  BGW: "Basingstoke West",
  BHN: "Bath North",
  BID: "Bidford",
  BIE: "Bicester East",
  BIF: "Broughton-in-Furness",
  BIG: "Biggleswade",
  BIL: "Billinghay",
  BIN: "Biddenden",
  BIR: "Birdlip",
  BIS: "Bishop Auckland",
  BKN: "Bockleton",
  BKY: "Brinkley Church",
  BLA: "Blakehill Farm",
  BLB: "Barnstaple  Bridge",
  BLD: "Blandford",
  BLE: "Blenheim N",
  BLF: "Blaenau Ffestiniog",
  BLG: "Ballinluig",
  BLH: "Balloch",
  BLI: "Blidworth",
  BLK: "Blakeney Point",
  BLN: "Blanchland",
  BLO: "Bolsover SW",
  BLR: "Blair Atholl",
  BLS: "Barnsley S",
  BLW: "Barnsley W",
  BLY: "Bletchley",
  BMA: "Balmaha",
  BMC: "Brayford",
  BMM: "Brynamman",
  BMR: "Braemar East",
  BMS: "Barmouth Station",
  BNG: "Bingham",
  BNK: "Brinkworth",
  BNS: "Burn South-West",
  BNV: "Ben Nevis",
  BNW: "Bicester North West",
  BO1: "Booker SW",
  BO4: "Turville Windmill",
  BO5: "Rockwell End",
  BOA: "Bridge of Avon",
  BOB: "Booker M40 Bridge",
  BOC: "Bridge of Cally",
  BOD: "Bodiam",
  BOG: "Bridge of Gaur",
  BOL: "Bootle",
  BOM: "Bodmin SW",
  BON: "Boncath",
  BOO: "Booker Airfield",
  BOR: "Boroughbridge",
  BOS: "Boston",
  BOT: "Bottesford",
  BOU: "Bourne",
  BOV: "Bovey Tracey",
  BOW: "Bourton-on-the-water",
  BOZ: "Bozeat",
  BPT: "Bridport",
  BR1: "Bognor Regis Gliding Club",
  BR2: "Bognor Domes",
  BRC: "Brackley South",
  BRD: "Bradbury",
  BRE: "Brecon",
  BRF: "Bradford-on-avon",
  BRG: "Brenig",
  BRH: "Brough",
  BRI: "Bridgnorth",
  BRK: "Broad Oak",
  BRL: "Brill",
  BRM: "Bromsgrove",
  BRN: "Burn",
  BRO: "Broadway",
  BRP: "Brampton",
  BRR: "Brora",
  BRS: "Braemar Stadium",
  BRT: "Brent Tor",
  BRU: "Bruton",
  BRY: "Bromyard",
  BRZ: "Brenzett",
  BS1: "Bury St Edmunds S",
  BS2: "Bury St Edmunds N",
  BSE: "Bury St Edmunds",
  BSN: "Basingstoke N",
  BSS: "Bunessan Pier",
  BSW: "Brecon SW",
  BT2: "Bassenthwaite E",
  BTH: "Bassenthwaite Lake NW",
  BTL: "Battle",
  BTN: "Bridlington",
  BTR: "Ballater",
  BTT: "Buttermere",
  BUB: "Burbage",
  BUC: "Buckingham",
  BUD: "Bude",
  BUG: "Burley Gate",
  BUH: "Burnhope Reservoir",
  BUI: "Builth Wells",
  BUK: "Buckfastleigh",
  BUL: "Bullington",
  BUN: "Bungay",
  BUS: "Burton upon Stather",
  BUT: "Butser Hill",
  BUX: "Buxton",
  BUY: "Beauly",
  BVR: "Belvoir",
  BVT: "Bovington",
  BWE: "Bridgwater E",
  BWL: "Bwlch",
  BYT: "Blyth",
  CAA: "Callander NE",
  CAC: "Candover Church",
  CAD: "Callander",
  CAE: "Canterbury East",
  CAH: "Castle Howard",
  CAI: "Cairnwell",
  CAL: "Calvert Rail Junction",
  CAN: "Cannock",
  CAO: "Canonbie",
  CAR: "Carlton Moor",
  CAS: "Cambridge South",
  CAT: "Canterbury",
  CAX: "Caxton Gibbet",
  CBA: "Carter Bar",
  CBC: "Conisbrough Castle",
  CBG: "Creagan Bridge",
  CBK: "Carisbrooke Castle",
  CBN: "Chilbolton",
  CBR: "Carrbridge",
  CCB: "Catacol Bridge",
  CCC: "Carreg Cennen Castle",
  CCH: "Castle Combe",
  CCK: "Castle Carrock Dam NW",
  CCL: "Crickhowell",
  CCR: "Clay Cross Reservoir",
  CCX: "Cadbury Cross",
  CDB: "Cromdale Spey Bridge",
  CDI: "Cader Idris",
  CDK: "Clodock",
  CDO: "Castle Douglas SW",
  CDS: "Clattershaws Dam S",
  CDW: "Coldwaltham",
  CER: "Cerne Abbas",
  CES: "Cowes",
  CFB: "Chollerford Bridge",
  CFE: "Cranwell Finish East",
  CFF: "Crieff",
  CFN: "Chalford North",
  CGB: "Calgary Beach Car Park",
  CGF: "Corgarf",
  CGI: "Craigellachie",
  CGL: "Croglin",
  CGN: "Cragganmore",
  CGT: "Cherington",
  CHA: "Chard",
  CHB: "Charlbury",
  CHC: "Chipping Campden",
  CHD: "Chesterfield",
  CHE: "Chedworth",
  CHI: "Chichester W",
  CHK: "Chirk",
  CHM: "Charlton Mires",
  CHN: "Chipping Norton",
  CHO: "Chorley West",
  CHP: "Chipping",
  CHR: "Charterhall Field",
  CHS: "Chelmsford S",
  CHT: "Chatteris",
  CHU: "Church Houses",
  CHV: "Chieveley",
  CHW: "Charwelton",
  CIL: "Castle Island Laggan",
  CIN: "Cinderford",
  CIR: "Cirencester Church",
  CIW: "Cirencester West",
  CKL: "Chicklade",
  CL2: "Challock Chalk Pit",
  CL3: "Challock East",
  CLA: "Claydon",
  CLC: "Clacton E",
  CLD: "Culdrose A/f",
  CLE: "Clee",
  CLH: "Culmhead airfield",
  CLI: "Clitheroe",
  CLK: "Challock",
  CLL: "Carlisle",
  CLM: "Chilham",
  CLN: "Calne W",
  CLO: "Clova",
  CLP: "Clyffe Pypard",
  CLR: "Clare Church",
  CLS: "Culmstock",
  CLT: "Corran Lighthouse",
  CLU: "Clunas",
  CLV: "Cleeve Hill",
  CLW: "Carloway",
  CLY: "Callaly Castle",
  CME: "Cheltenham East",
  CML: "Carmodle",
  CMN: "Carmarthen",
  CMO: "Cockermouth",
  CNB: "Caerleon bridge",
  CNE: "Canterbury North East",
  CNL: "Connel",
  CNN: "Corndon Hill",
  CNO: "Carno",
  CNR: "Chinnor",
  CNW: "Cirencester nw",
  CNY: "Conwy Bridge",
  COB: "Corby South",
  COC: "Colchester",
  COD: "Coldstream",
  COE: "Corwen NE",
  COF: "Crocketford",
  COG: "Corby Glen",
  COH: "Coldingham",
  COK: "Cocking",
  COM: "Comrie",
  CON: "Condover",
  COR: "Corby",
  COS: "Cosford Junction",
  COT: "Colt Crag Reservoir",
  COU: "Coupar Angus",
  COW: "Colchester West",
  CP1: "Camphill start/finish south",
  CP2: "Camphill Chimney",
  CPH: "Camphill",
  CPN: "Clapham Reservoir N",
  CPS: "Chepstow S",
  CPW: "Chippenham W",
  CRA: "Cranwell North",
  CRB: "Cranbrook",
  CRC: "Crick",
  CRD: "Cricklade",
  CRE: "Crediton Station",
  CRF: "Crail",
  CRG: "Cerrig",
  CRI: "Crianlarich",
  CRK: "Crewkerne",
  CRL: "Crowland A/f",
  CRM: "Crymych Mast",
  CRN: "Crinan",
  CRO: "Crowland Bridge",
  CRP: "Cromer Pier",
  CRR: "Carron",
  CRW: "Crediton West",
  CRY: "Cray Reservoir",
  CSD: "Chirnside",
  CSE: "Canterbury South East",
  CSF: "Cosford Airfield",
  CSK: "Crask Bridge",
  CSN: "Coniston",
  CSS: "Cross Hands",
  CSW: "Colsterworth",
  CTH: "Crathie Bridge",
  CTK: "Catterick",
  CTP: "Clows Top",
  CU2: "Clunbury Hill",
  CUL: "Cullompton",
  CUN: "Clun",
  CUP: "Cupar",
  CUR: "Currock Hill",
  CVN: "Craven Arms",
  CWA: "Chipping Warden",
  CWC: "Crowcombe Court",
  CWE: "Crewe East",
  CWN: "Corwen",
  CWS: "Cwmbran SW",
  CWT: "Chatsworth",
  CWV: "Carsington Water Visitors Centre",
  CWW: "Conwy W",
  CWY: "Conwy S",
  DAL: "Dallachy",
  DAM: "Dalmally",
  DAN: "Danby",
  DAR: "Darlington",
  DAW: "Darwell",
  DBN: "Dunblane",
  DBR: "Devil's Bridge",
  DBY: "Diddlebury",
  DCT: "Didcot Rail Bridge",
  DCW: "Didcot West",
  DDK: "Devil's Dyke",
  DEA: "Deal",
  DED: "Deddington",
  DEN: "Denbigh",
  DEP: "Depden Water Tower",
  DER: "Derwent",
  DET: "Detling",
  DEV: "Devizes",
  DFF: "Duffield",
  DFU: "Dalton-in-Furness",
  DIN: "Dingwall",
  DIS: "Diss",
  DIT: "Ditchlingbeacon",
  DKD: "Dunkeld",
  DKY: "Dunkery Beacon",
  DLB: "Dale Bridge",
  DLS: "Dallas",
  DLT: "Dalston",
  DMN: "Duntulm N",
  DNB: "Dunbar SE",
  DNE: "Durham Northeast",
  DNG: "Dunning",
  DNN: "Dunoon",
  DNT: "Duntulm",
  DNW: "Doncaster Northwest",
  DOC: "Docking",
  DOG: "Dolgellau",
  DOL: "Dollar",
  DON: "Doncaster",
  DOR: "Dorchester",
  DOU: "Doune",
  DOV: "Dover Marina",
  DOW: "Downham Market",
  DRB: "Droma Bridge",
  DRI: "Driffield",
  DRL: "Darlton",
  DRO: "Droitwich",
  DRS: "Denbigh Ridge S",
  DRU: "Drumshade",
  DSE: "Daventry SE",
  DSW: "Dursley SW",
  DTN: "Donington",
  DUB: "Dulnain Bridge",
  DUC: "Duncton",
  DUF: "Dufftown",
  DUL: "Dulverton",
  DUM: "Dumfries",
  DUN: "Dunstable Airfield",
  DUR: "Durham",
  DUS: "Duns",
  DUT: "Dufton",
  DUY: "Dursley NW",
  DVN: "Daventry N",
  DWI: "Dalwhinnie",
  DYN: "Danbury N",
  DYS: "Dyserth",
  EAG: "Eaglescott",
  EAR: "Earith",
  EAS: "Easterton",
  EAT: "Eastgate",
  EAW: "Eastwell",
  ECN: "Eckford N",
  EDG: "Edgehill",
  EDW: "Edgehill West",
  EDZ: "Edzell",
  EGG: "Eggesford N",
  ELK: "Elkstone S",
  ELL: "Ellesmere",
  ELM: "Elmswell W",
  ELT: "East Linton",
  ELV: "Elvanfoot",
  ELY: "Ely",
  ENS: "Enstone",
  ENW: "Eastbourne NW",
  ETC: "Etchingham",
  ETL: "Etal",
  ETT: "Ettington",
  EVE: "Evesham",
  EWW: "Ennerdale Water W",
  EYE: "Eyebrook",
  FAK: "Fakenham",
  FAL: "Falgunzeon",
  FAR: "Faringdon",
  FAV: "Faversham",
  FAW: "Falkirk West",
  FBG: "Fraserburgh",
  FBR: "Fontburn Reservoir",
  FE1: "Feshie Airstrip",
  FE2: "Feshie Start N",
  FE3: "Feshie Descent Point",
  FE5: "Feshie S",
  FEA: "Fearnan",
  FEN: "Fenny Compton",
  FER: "Ferness",
  FES: "Feshiebridge",
  FET: "Fettercairn",
  FEX: "Felixstowe Pier",
  FFD: "Farnsfield",
  FFI: "Fforest Inn",
  FFR: "Forfar",
  FHI: "Fan Hir",
  FHP: "Fownhope",
  FIB: "Firle Beacon",
  FIL: "Filey",
  FIM: "Finmere",
  FIN: "Finavon",
  FIS: "Fishguard",
  FLA: "Flamborough",
  FMA: "Four Marks",
  FNE: "Fort William NE",
  FNW: "Falmouth NW",
  FOA: "Fort Augustus",
  FOD: "Fordoun",
  FOL: "Folkestone",
  FON: "Fontwell Park Roundabout",
  FOR: "Fordingbridge",
  FOS: "Foston",
  FOV: "Fovant",
  FRE: "Freuchie",
  FRI: "Fridaythorpe",
  FRO: "Frome",
  FRW: "Framlingham",
  FTW: "Fort William",
  GA2: "Gainsborough Power Station",
  GAA: "Galashiels",
  GAB: "Garboldisham",
  GAF: "Garforth",
  GAG: "Gargrave West",
  GAI: "Gainsborough",
  GAL: "Gallowfauld",
  GAR: "Garten",
  GAT: "Gateshead East",
  GAY: "Gaydon",
  GBB: "Gribbin Head",
  GBE: "Great Bedwyn",
  GBR: "Glasbury Bridge",
  GCB: "Gloucester Canal Bridge",
  GDB: "Glen Dee Bridge",
  GDE: "Glyndebourne",
  GDF: "Great Dun Fell",
  GDN: "Gordon",
  GES: "Gretna Services",
  GFD: "Glenfiddich Lodge",
  GFG: "Glenfarg Reservoir E",
  GFL: "Glen Falloch",
  GHD: "Garsdale Head",
  GIF: "Gifford",
  GIL: "Gillingham",
  GIO: "Giosla",
  GIS: "Gisburn",
  GLA: "Glastonbury",
  GLB: "Gelt Bridge",
  GLD: "Gilsland Village",
  GLE: "Glendevon",
  GLF: "Glenforsa",
  GLN: "Gleneagles",
  GLS: "Gloucester South",
  GLT: "Glenlatterach Dam N",
  GLY: "Gairlochy",
  GNS: "Grains",
  GO2: "Goole N",
  GOO: "Goole NE",
  GOR: "Goring",
  GPN: "Great Ponton",
  GR1: "Gransden NW",
  GRA: "Grantham",
  GRC: "Grasmere Church",
  GRF: "Great Ashfield",
  GRI: "Grimwith Reservoir",
  GRL: "Gransden Lodge",
  GRM: "Great Malvern",
  GRN: "Greenlaw",
  GRO: "Grosmont",
  GRS: "Grassington",
  GRT: "Great Rundale Tarn",
  GRW: "Grafham Water",
  GSE: "Grantshouse",
  GSS: "Glassonby",
  GTN: "Grantown",
  GTO: "Great Orme",
  GTW: "Great Witley",
  GUI: "Guisborough",
  GUW: "Guisborough SW",
  GVE: "Garve",
  GWD: "Goodwood Grandstand",
  GYS: "Great Yarmouth S",
  HA2: "Halton West",
  HAB: "Hay Bluff",
  HAD: "Halesland",
  HAE: "Halesworth",
  HAI: "Hailsham",
  HAK: "Hawick",
  HAL: "Halton",
  HAN: "Harrogate North",
  HAR: "Harting",
  HAS: "Hastings",
  HAT: "Hatherleigh",
  HAV: "Haverhill",
  HAW: "Hawkhurst",
  HAY: "Hay-on-wye",
  HB1: "HB start west",
  HB2: "HB start north",
  HB3: "HB start east",
  HB4: "HB East",
  HB5: "HB control point east",
  HB7: "HB Finish West",
  HBR: "Haydon Bridge",
  HCM: "Hinderclay Meadows Air-Strip",
  HDD: "Haddington",
  HDL: "Helmsdale",
  HDW: "Hardwick",
  HEC: "Hereford Cathedral",
  HEE: "Heathfield E",
  HEL: "Helensburgh",
  HER: "Hereford Racecourse",
  HES: "Henstridge",
  HEU: "Heugh Head",
  HEX: "Hexham",
  HGM: "Highham",
  HHL: "Hembury Hill",
  HI1: "Hinton Start W",
  HI2: "Hinton Start N.",
  HIC: "Hinckley",
  HIN: "Hinton in the Hedges",
  HLH: "Hunstanton Lighthouse",
  HLM: "Helmsley",
  HLS: "Harlech South",
  HNN: "Hungerford North",
  HNT: "Huntercombe",
  HOL: "Holsworthy",
  HON: "Honeybourne",
  HOR: "Horncastle",
  HOT: "Hesket Old Town",
  HOW: "Howden Dam",
  HPY: "Harpley",
  HRM: "Horam",
  HRR: "Harrietsham",
  HRT: "Hartside Top",
  HSE: "Hawes",
  HSG: "Hathersage",
  HSM: "Hornsea Mere",
  HTN: "Honington Airfield",
  HTY: "Huntly",
  HUD: "Hope Under Dinmore",
  HUL: "Hullavington M4/J17",
  HUM: "Humber Bridge",
  HUN: "Hungerford",
  HUR: "Hurstbourne Tarrant",
  HUS: "Husbands Bosworth",
  HVS: "Havant S",
  HVT: "Havant NW",
  HVW: "Haverfordwest",
  HWB: "Halfway Bridge",
  HWH: "Halfway House",
  HWL: "Haltwistle",
  HYE: "Hay East",
  ILF: "Ilfracombe",
  ILS: "Ilsley",
  INC: "Insch",
  ING: "Ingleton",
  INK: "Inchkinloch",
  INV: "Inverary",
  IPE: "Ipswich E",
  ISE: "Inverness SE",
  ISL: "Islip",
  IVS: "Invershin",
  IVY: "Ivybridge East",
  IWE: "Iwerne Minster",
  JED: "Jedburgh",
  KCA: "Kielder Castle",
  KCG: "Kincraig",
  KDL: "Kendal",
  KEE: "Keevil",
  KEK: "Keswick",
  KEL: "Kelso",
  KEM: "Kempock Point",
  KEN: "Kenley",
  KES: "Kettering South",
  KEX: "Kexby Bridge",
  KGS: "Kingsclere",
  KIB: "Kinbrace",
  KIC: "Kinclaven",
  KID: "Kidderminster",
  KIE: "Kielder Reservoir",
  KIG: "Kingussie",
  KIK: "Kirkharle",
  KIL: "Kilcreggan",
  KIM: "Kingham",
  KIN: "Kineton",
  KIP: "Kippen",
  KIR: "Kirton-in-lindsey",
  KLE: "Kellie Castle",
  KLH: "Kilham",
  KLN: "Killin",
  KLO: "Kirkby Lonsdale",
  KLT: "Kinlet",
  KLY: "King's Lynn",
  KME: "Kentmere",
  KML: "Kirkmichael",
  KMR: "Kenmore",
  KNA: "Knaresborough",
  KNI: "Knighton",
  KNO: "Knowstone",
  KNW: "Knighton West",
  KRB: "Kirkbymoorside",
  KRM: "Kirriemuir",
  KSB: "Kingston Bagpuize",
  KST: "Kirkby Stephen Station",
  KTH: "Keith",
  KTN: "Kilmington",
  KWE: "Kinlochewe",
  KWK: "Knightwick",
  KWO: "Kibworth",
  KYL: "Kyleakin",
  LA1: "Lasham Start Southeast",
  LA2: "Lasham Start East",
  LA3: "Lasham Church",
  LA4: "Lasham Start South",
  LA5: "Lasham West",
  LA6: "Lasham Start North",
  LAD: "Lauder",
  LAE: "Llanelli East",
  LAG: "Langport",
  LAI: "Lairg",
  LAL: "Lake Alaw Reservoir",
  LAM: "Lampeter",
  LAN: "Langham",
  LAP: "Lapford",
  LAR: "Lattrig",
  LAS: "Lasham Finish North",
  LAT: "Latheron",
  LAU: "Launceston",
  LBD: "Longbridge Deverill",
  LBE: "Loch Bradan E",
  LBN: "Lambourn",
  LBR: "Laggan Bridge",
  LBU: "Lochbuie",
  LBZ: "Leighton Buzzard NE",
  LCE: "Llyn Celyn NW",
  LCH: "Lanchester",
  LCL: "Lower Clopton",
  LDB: "Lochindorb Castle",
  LDM: "Laggan Dam",
  LDN: "Loddon",
  LDR: "Lindores",
  LEA: "Lochearnhead",
  LEB: "Lake Eiddew-bach",
  LED: "Ledbury",
  LEH: "Leadenham",
  LEI: "Leicester M1 Services",
  LEK: "Leck",
  LEL: "Loch Eil West",
  LEN: "Leicester North",
  LEO: "Leominster",
  LER: "Loch Errochty East",
  LES: "Leicester South",
  LET: "Leighterton",
  LEW: "Lewes North",
  LEY: "Leyburn",
  LEZ: "Leighton Buzzard",
  LFC: "Lindisfarne Castle",
  LFN: "Llanfyllin",
  LGG: "Loch Laggan North East",
  LGI: "Lochgilphead",
  LGN: "Loch Garry N",
  LGO: "Lochgoilhead",
  LIS: "Lismore",
  LIT: "Littleport",
  LKD: "Liskeard SE",
  LLA: "Llangollen",
  LLB: "Llanbadarn",
  LLC: "Llanfair Caereinion",
  LLD: "Llandovery",
  LLE: "Lleweni Parc",
  LLG: "Llangynidr Bridge",
  LLI: "Llanidloes",
  LLM: "Llanymynech",
  LLN: "Llanrwst",
  LLO: "Llandeilo",
  LLS: "Llantysilio",
  LLT: "Loch Lomond Tarbet",
  LLW: "Llandrindod Wells",
  LMB: "Lochmaben",
  LMD: "Loch Mullardoch East",
  LMO: "Loch Morlich",
  LMR: "Ledmore",
  LMU: "Loch Muick",
  LMV: "Long Marston Church",
  LMW: "Leominster NW",
  LMY: "Loch Moy",
  LNE: "Lichfield NE",
  LOA: "Lochailort",
  LOC: "Lockerbie",
  LOD: "Linn of Dee",
  LOG: "Loch Gairloch SE",
  LOI: "Loch Laidon Island",
  LOK: "Loch Kinord",
  LOL: "Loch Lochy North East",
  LOM: "Lake of Menteith",
  LON: "Longleat",
  LOQ: "Loch Quoich East",
  LOU: "Louth",
  LOW: "Lowick",
  LRI: "Little Rissington",
  LRK: "Lanark",
  LSA: "Llansannan",
  LSL: "Llandysul",
  LSN: "Loch Seilich N",
  LSS: "Liss",
  LSU: "Long Sutton",
  LTF: "Langtoft",
  LTN: "Longtown",
  LUD: "Ludlow",
  LUN: "Luncarty",
  LUS: "Lussa Loch S",
  LUT: "Lutterworth",
  LVE: "Loch Venachar",
  LVN: "Lavenham",
  LWL: "Low Lorton",
  LWN: "Lewes nw",
  LYB: "Llwyngwril Bridge",
  LYD: "Leyland North East",
  LYN: "Lyneham a/f",
  LYR: "Ladybower Reservoir",
  LYV: "Lyveden",
  MAC: "Machynlleth Station",
  MAD: "Market Deeping",
  MAE: "Marlborough E",
  MAH: "Market Harborough",
  MAI: "Maidstone East",
  MAL: "Malton",
  MAM: "Malmesbury",
  MAN: "Manton",
  MAR: "Marlborough",
  MAS: "Masham",
  MAT: "Matlock",
  MAW: "Market Weighton",
  MBL: "Mablethorpe",
  MBO: "Market Bosworth",
  MBR: "Montford Bridge",
  MBU: "Melbury Bubb",
  MBY: "Manby",
  MCH: "March",
  MDN: "Maidstone North",
  MEA: "Measham",
  MEE: "East Meon",
  MEL: "Melksham",
  MEM: "Membury",
  MEN: "Mendlesham",
  MER: "Mere",
  MET: "Melton Mowbray",
  MEW: "West Meon Hut",
  MEX: "Mexborough S",
  MFD: "Mansfield NE",
  MGH: "Margery Hill",
  MHT: "Minchinhampton",
  MIC: "Micheldever",
  MIG: "Mingary Pier",
  MIL: "Milfield",
  MIM: "Midhurst Mast",
  MIN: "Mintlaw",
  MIT: "Milnthorpe",
  MIW: "Midhurst West",
  MLL: "Mellon Charles",
  MLM: "Melmerby",
  MLN: "Molton",
  MLT: "Milton",
  MLY: "Madley",
  MNE: "Maryport NE",
  MNS: "Menai Strait",
  MNW: "Millom NW",
  MOK: "Monkton",
  MOM: "Monmouth",
  MON: "Montgomery",
  MOO: "Muir of Ord",
  MOP: "Morpeth",
  MOR: "Moreton-in-marsh",
  MOS: "Mossat",
  MOT: "Mortimer Church",
  MOU: "Moulton Church",
  MOY: "Moy Lodge",
  MRE: "Margate E",
  MRN: "Market Rasen",
  MRY: "Maryport",
  MSE: "Mansfield SE",
  MTD: "Methwold",
  MTF: "Mottisfont Station",
  MTH: "Moota Hill",
  MTM: "Melton Mast",
  MTR: "Montrose",
  MUD: "Mudford Gate",
  MUM: "Mumbles Head",
  MUN: "Mundford",
  MUR: "Mursley",
  MUT: "Murton",
  MVN: "Methven",
  MWD: "Mallwyd",
  MWP: "Middle Wallop",
  MY2: "Mynd S",
  MY3: "Mynd N",
  MYN: "Mynd",
  MZI: "Monzie",
  NAB: "New Abbey",
  NAE: "Naseby East",
  NAI: "Nailsworth",
  NAN: "Narberth N",
  NAW: "Naseby West",
  NBR: "Norham Bridge",
  NCH: "Newchurch",
  NDL: "Needles",
  NDU: "North Duffield",
  NEA: "Northleach East",
  NEC: "New Cumnock",
  NED: "New Deer",
  NEE: "Needham Market E",
  NEF: "Nefyn",
  NEG: "New Galloway",
  NEM: "Newmill",
  NEN: "Newbury N",
  NES: "Newbury South",
  NET: "Newtown",
  NEW: "Newbury Racecourse",
  NH2: "North Hill N",
  NHL: "North Hill",
  NLE: "Northleach",
  NMT: "Newmarket",
  NOC: "Newcastle on Clun",
  NOR: "Norman Cross",
  NOS: "Northampton South",
  NOW: "Northampton West",
  NPT: "Newport Pagnall",
  NRA: "Nunraw Abbey",
  NRT: "Northallerton",
  NST: "Newton Stewart",
  NTA: "N Tawton",
  NTB: "Nethybridge",
  NTN: "Neenton",
  NUN: "Nunney",
  NWK: "Newark",
  NWT: "Newent",
  NY1: "Nympsfield Finish East",
  NY2: "Nympsfield Finish West",
  NYM: "Nympsfield",
  OAE: "Oakham E",
  OAK: "Oakington",
  OBA: "Oban Airfield",
  OBN: "Oban Station",
  ODI: "Odiham",
  OGB: "Ogbourne",
  OKE: "Okehampton East",
  OLL: "Ollerton",
  OLN: "Olney",
  ORA: "Old Radnor",
  OSB: "Osbournby",
  OSW: "Oswestry",
  OTM: "Ottercops Moss",
  OUN: "Oundle",
  OUS: "Ousby E",
  OVE: "Overton",
  OXF: "Oxford East",
  OXM: "Oxford M40 Services",
  OXN: "Oxford North",
  OXS: "Oxford South",
  OXT: "Oxton",
  PA2: "Pateley SE",
  PAD: "Paddock Wood",
  PAN: "Pangbourne",
  PAP: "Papworth",
  PAR: "Parham",
  PAT: "Pateley Bridge",
  PCM: "Pencombe",
  PCN: "Porthcawl North",
  PCS: "Portmoak Caravan Site",
  PCT: "Pontefract",
  PEB: "Porthmadog East Bridge",
  PEE: "Peebles",
  PEI: "Penrith",
  PEM: "Pembroke Dock",
  PEN: "Pendock",
  PET: "Peterborough",
  PEV: "Peveril Castle",
  PEW: "Pewsey",
  PGO: "Pitsligo",
  PIC: "Pickenham",
  PIE: "Penrith East",
  PIT: "Pitsford",
  PKG: "Pickering",
  PLE: "Peterlee",
  PLM: "Plumpton",
  PLU: "Pluckley",
  PLY: "Pitlochry",
  PNS: "Pontsticill Reservoir",
  PNT: "Portsmouth N",
  PNW: "Parham NW",
  PO1: "Portmoak NW",
  PO2: "Portmoak W",
  POA: "Potarch Bridge",
  POC: "Pocklington",
  POF: "Pontypool Folly",
  POH: "Pontesbury Hill",
  POL: "Polegate",
  POP: "Popham",
  POR: "Portmoak Clubhouse",
  POS: "Pocklington South",
  POT: "Potton",
  POW: "Powburn",
  PPE: "Pontypool E",
  PPN: "Pontypool N",
  PPP: "Port Appin",
  PR1: "Park Control Point E",
  PRE: "Presteigne",
  PRI: "Prince's Risborough",
  PRK: "Park-the",
  PRN: "Preston North",
  PRT: "Portree",
  PSE: "Pershore se",
  PSH: "Portesham",
  PTD: "Pontardulais",
  PTE: "Port Eynon",
  PTF: "Petersfield South",
  PTH: "Perth",
  PTM: "Porthmadog",
  PTN: "Pirton",
  PTR: "Portsmouth Tower",
  PTW: "Petersfield West",
  PVY: "Pevensey",
  PWN: "Penwhirn Reservoir",
  PWW: "Pwllheli West",
  PYE: "Plymouth E",
  PYF: "Pen-y-Fan",
  PYS: "Prestatyn S",
  PYW: "Plymouth W",
  RAB: "Ramsbury",
  RAD: "Radstock",
  RAG: "Raglan",
  RAM: "Ramsey",
  RAN: "Rannoch Station",
  RAR: "Ravensthorpe Reservoir",
  RAV: "Ravenglass N",
  RBR: "Roybridge",
  RBS: "Rosebush",
  RBY: "Rothbury",
  RDN: "Rattlesden A/F Centre",
  RDW: "Radway",
  REA: "Reading West",
  REE: "Reedham",
  RET: "Retford",
  RHD: "Rattray Head",
  RHI: "Rhigos",
  RHO: "Rhossdhu House",
  RHU: "Rhuddlan",
  RHY: "Rhayader",
  RI2: "Rivar Hill North",
  RIC: "Richmond",
  RID: "Ridgewell Church",
  RIN: "Ringmer",
  RIP: "Ripon",
  RIV: "Rivar Hill",
  RIW: "Ridgewell Field",
  RKB: "Rockbourne",
  RNE: "Rugby Northeast",
  RNI: "Rhynie",
  ROA: "Roadford",
  ROC: "Rochester",
  ROD: "Rodney's Pillar",
  ROH: "Rothes",
  ROS: "Ross-on-wye",
  ROT: "Rotherham",
  ROY: "Royston",
  RSE: "Redruth SE",
  RSN: "Rosneath",
  RSY: "Rothesay",
  RTH: "Rosthwaite",
  RU1: "Rufforth South",
  RUB: "Rubha Reidh",
  RUF: "Rufforth",
  RUG: "Rugby",
  RUN: "Ruthin NE",
  RUS: "Rushden",
  RUW: "Ruthin West",
  RVN: "Ruthven",
  RWD: "Rutland Water Dam",
  RYB: "Rydal Bridge",
  RYD: "Ryde",
  RYE: "Rye",
  SAC: "Sackville",
  SAL: "Salisbury Cathedral",
  SAN: "Sandhill Farm",
  SAP: "Shap",
  SAR: "Sarnesfield",
  SAS: "Salisbury South",
  SAW: "Sandwich",
  SAX: "Saxthorpe",
  SB2: "Saltby NW",
  SBB: "Strubby",
  SBR: "Santon Bridge",
  SBT: "Simonsbath",
  SBY: "Saltby",
  SCB: "Scarborough",
  SCF: "Scalford Church",
  SCL: "Scoulton",
  SCN: "Strathcarron",
  SCO: "Scourie",
  SCP: "St Catherine's Point",
  SCU: "Scunthorpe N",
  SDV: "St Davids",
  SDW: "Seighford South-West",
  SE2: "Seighford Hangar",
  SEA: "Seaford East",
  SED: "Sedbergh",
  SEL: "Selset Reservoir",
  SEN: "Sennybridge",
  SET: "Settle",
  SEV: "Severn Bridge N",
  SEW: "Sheffield West",
  SFB: "Stamford Bridge",
  SFD: "Sleaford",
  SFE: "Sheffield East",
  SFW: "Stratford West",
  SGW: "Stelling Windmill",
  SH2: "Shobdon NW",
  SH3: "Shobdon E",
  SH4: "Shobdon West",
  SHA: "Shaftesbury",
  SHB: "Sherborne",
  SHD: "Stoer Head",
  SHE: "Sheffield North",
  SHI: "Shirebrook Station",
  SHL: "Salt Hill Mast",
  SHM: "Shepton Mallett",
  SHO: "Shobdon",
  SHP: "Shipston-on-stour",
  SHS: "Shrewsbury",
  SHT: "Shottaton",
  SHV: "Shrivenham N",
  SHW: "Shrewsbury NW",
  SHY: "Shawbury",
  SID: "Sidmouth",
  SIL: "Silverstone",
  SIS: "Stirling South",
  SIT: "Sittingbourne",
  SIW: "Stirling Northwest",
  SIX: "Sixpenny Handley",
  SKB: "Stickney Bridge",
  SKE: "Skeffington",
  SKS: "Stocks Reservoir South West",
  SKW: "Selkirk W",
  SLE: "Sleap",
  SLL: "Silloth",
  SLS: "Selsey Bill",
  SMA: "Smailholm Tower",
  SMB: "Six Mile Bottom",
  SML: "St Mary's Loch",
  SMM: "St Michael's Mount",
  SN2: "Snitterfield SW",
  SNA: "Snainton",
  SNI: "Snitterfield",
  SNO: "Swindon N",
  SNP: "Staindrop",
  SNS: "St Neots S",
  SNW: "Stratford NW",
  SOA: "Stratford",
  SOF: "Sutton-on-forest",
  SOH: "Soham",
  SOS: "Stokenchurch South",
  SOU: "Southam",
  SOW: "Stow",
  SPA: "Spalding",
  SPB: "Sharperton Bridge",
  SPD: "Spey Dam",
  SPE: "Spean Bridge",
  SPH: "Staplehurst",
  SPI: "Spilsby",
  SPL: "Spittal of Glenshee",
  SPN: "Spinningdale Bridge",
  SPP: "Sheppey E",
  SPS: "Shap S",
  SPT: "Shipton",
  SPU: "Spurn Head North",
  SRE: "Stroud E",
  SRN: "Strontian",
  SRR: "Storrington SW",
  SSO: "Sheffield South",
  SSW: "Stoke SW",
  STA: "Stafford",
  STB: "St Boswells",
  STC: "Stokenchurch Tower",
  STD: "Stradishall",
  STE: "Steyning",
  STF: "St Fillans",
  STH: "Stanhope",
  STI: "Stirling",
  STK: "Stockbridge",
  STN: "St Neots",
  STO: "Stone",
  STP: "Stourport",
  STR: "Strachan",
  STS: "Stony Stratford",
  STT: "Stretton",
  STU: "Sturminster Newton",
  STW: "Stow-on-the-wold",
  SU1: "Sutton Bank Start S",
  SU2: "Sutton Bank Start W",
  SU3: "Sutton Bank Control Point N",
  SU4: "Sutton Bank Control Point S",
  SUD: "Sudbury",
  SUT: "Sutton Bank",
  SUW: "Shipton under Wychwood",
  SVN: "Strathaven",
  SWD: "Snowdon",
  SWE: "Swindon East",
  SWH: "Shawhead",
  SWL: "Swalcliffe",
  SWM: "Southwell Minster",
  SWS: "Swindon South",
  SWT: "Swainsthorpe",
  SWW: "Swindon W",
  SXB: "Saxby Church",
  SYB: "Syre Bridge",
  TA1: "Talgarth NW",
  TA2: "Talgarth W",
  TA3: "Talgarth S",
  TAD: "Tarland",
  TAL: "Talgarth",
  TAR: "Tarbert",
  TAU: "Taunton",
  TAV: "Tavistock",
  TB1: "Tibenham Start SE",
  TBK: "Troutbeck",
  TBN: "Tetbury North",
  TBS: "Tetbury South",
  TBW: "Tetbury West",
  TBY: "Tenby",
  TCM: "The Camp",
  TDL: "Tindale",
  TEB: "Tebay",
  TED: "Tenterden",
  TEE: "Telford East",
  TEG: "Temple Guiting",
  TEL: "Telford",
  TEN: "Tenbury Wells",
  TES: "Telford South",
  TEV: "Teviothead",
  TEW: "Tewkesbury North",
  TFS: "Tarfside",
  THA: "Thame Church",
  THD: "Todhead",
  THE: "Thetford",
  THG: "Thorngumbald",
  THI: "Thirsk",
  THM: "Thame Rail Bridge",
  THN: "Thornhill",
  THO: "Thornton",
  THP: "Thrapston",
  TIA: "Tintern Abbey",
  TIB: "Tibenham",
  TIC: "Tickhill",
  TID: "Tideswell Church",
  TIE: "Tiverton East",
  TIN: "Tomatin",
  TIP: "Tiptree",
  TIS: "Tisbury",
  TIV: "Tiverton",
  TNE: "Thornbury Northeast",
  TNW: "Telford NW",
  TOC: "Tockwith",
  TOD: "Toddington",
  TOG: "Tongue",
  TOK: "Torksey Viaduct",
  TOM: "Tomintoul",
  TON: "Tontine Inn",
  TOR: "Torver",
  TOW: "Towcester",
  TRE: "Tregaron",
  TRF: "Turriff",
  TRN: "Thorne",
  TRO: "Trowbridge",
  TRR: "Truro NE",
  TRU: "Truleigh",
  TRW: "Truro West",
  TRY: "Treyford",
  TSW: "Telford SW",
  TUJ: "Tuxford Rail Junction",
  TUL: "Tulla Loch East",
  TUM: "Tummel Bridge",
  TUW: "Tulla Loch West",
  ULL: "Ullswater",
  ULP: "Ulpha",
  ULV: "Ulverston",
  UPA: "Upavon Hangar W",
  UPL: "Ullapool",
  UPP: "Uppingham N",
  UPS: "Upper Sapey",
  UPW: "Upwood Hangar",
  USK: "Usk",
  UTT: "Uttoxeter",
  UWH: "Uffington White Horse",
  VRY: "Vyrnwy",
  WAB: "Waterbeck",
  WAL: "Walford",
  WAN: "Wantage",
  WAO: "Watton",
  WAR: "Warcop",
  WAS: "Washington",
  WAT: "Watford Gap",
  WAW: "Watch Water Reservoir",
  WBN: "Whiteburn",
  WBR: "Weldon Bridge",
  WBS: "Wetherby South",
  WBY: "Whitby Bridge",
  WCB: "Winchcombe",
  WCH: "Woodchurch Farm",
  WDD: "Widdrington Station",
  WDG: "Witheridge",
  WDM: "Windermere",
  WEB: "Westbury NE",
  WEC: "Westcott",
  WEG: "Wellington",
  WEL: "Welford",
  WEN: "Wendling",
  WES: "Westbury",
  WET: "Wetherby",
  WEY: "Weymouth",
  WFN: "Whitfield North",
  WGT: "Wigton",
  WGW: "Wing W",
  WH2: "Whitchurch Hants",
  WHD: "Whiddon Down",
  WHI: "Whitchurch Shropshire",
  WHM: "Whitehaven Marina",
  WHN: "Whittington",
  WHR: "Whiteadder Reservoir",
  WHT: "Whitstable",
  WHW: "Whitchurch Shropshire West",
  WIC: "Whickham",
  WIG: "Wingham",
  WIK: "Wick West",
  WIM: "Wimbleball",
  WIN: "Wincanton",
  WIS: "Wisbech",
  WIW: "Wilton West",
  WKB: "Warkworth Bridge",
  WKE: "Worksop East",
  WKW: "Wickwar",
  WLD: "West Lomond Hill",
  WLL: "Willersley",
  WLS: "Wells",
  WLT: "Waternish Point",
  WLW: "Worlingworth",
  WLY: "Woolley Down",
  WME: "Wormingford East",
  WML: "Wormelow",
  WMW: "Wormingford West",
  WNE: "Welshpool NE",
  WNT: "Westnewton",
  WNW: "Wantage Northwest",
  WO2: "Weston Finish Point",
  WOB: "Woburn Abbey",
  WOC: "Worcester Racecourse",
  WOD: "Woodall Services",
  WOE: "Woore",
  WOG: "Weston-on-the-green",
  WOL: "Wooler East",
  WOM: "Woburn",
  WON: "Walton on Naze Pier",
  WOO: "Wooler",
  WOR: "Worcester",
  WPL: "Withypool",
  WPR: "Wistlandpound Reservoir",
  WRA: "Wragby",
  WRK: "Workington",
  WRM: "Wormingford",
  WRO: "Wroughton",
  WSG: "Wimborne St Giles",
  WSL: "Winslow",
  WSM: "Wattisham",
  WSP: "Worksop",
  WTB: "Waterbeach N",
  WTH: "Worthing",
  WTM: "Worthen",
  WTN: "Watlington",
  WWE: "Wast Water E",
  WWW: "Wast Water W",
  WYL: "Wylye",
  WYM: "Wymondham",
  YAT: "Yate",
  YEO: "Yeovil Reservoir",
  YET: "Yetholm",
  YOE: "York East",
  YOR: "York",
  YTN: "Yeovilton",
  YTT: "Yattendon",
};

export default TURNPOINTS;
